joinmarket-webui/jam

src/components/Payment.jsx, src/components/Receive.jsx
this pull request contains some small ui improvements and bugfixes.
fix: 
- validate amount on payment page.
a value of zero will actually send the entire amount.
this is probably not what the user expects.
solving this by requiring the value to be greater than zero.
- correctly display qr code on receive page.
when navigating to the receive page with a specific account,
the qr code has not been loaded. this fix will ensure the account
type is an integer and hence the qrcode is loaded as expected.
ui: 
- use same width for value/account form elements
- select account via select box on payment page
- select account via select box on receive page
=> small ui improvements and bugfixes

src/components/CurrentWallet.jsx
Component `rb.Form.Check` renders as div which leads to a warning when placed inside a paragraph tag:
`Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.`
Removing the tag does not have a visual impact.
=> fix: prevent dom validation warning

src/components/CurrentWallet.jsx, src/components/DisplayAccountUTXOs.jsx, src/components/DisplayAccounts.jsx, src/components/DisplayUTXOs.jsx, src/utils.js
Adds a simple switch to show / hide wallet balances on the main page.
Hiding sensitive information such as balances is one of the best practices [mentioned in the Bitcoin design guidelines](https://bitcoin.design/guide/onboarding/protecting-a-wallet/#quickly-hiding-balances). 
Nothing fancy, maybe we should make it possible to hide balances app-wide in the future but for now I think this might be good enough.
=> Add switch to show / hide balances

src/components/App.jsx, src/components/CurrentWallet.jsx, src/components/DisplayAccountUTXOs.jsx, src/components/DisplayAccounts.jsx, src/components/DisplayUTXOs.jsx, src/components/Settings.jsx, src/context/SettingsContext.jsx, src/index.jsx
Adds a simple settings screen and moves the "show balance" and "display amounts in sats" switches there. Nothing fancy yet because I wanted to keep the pull request as small as possible. We can do UI improvements later.
The main addition is a [React Context](https://reactjs.org/docs/context.html) that persists settings in local storage and keeps those settings in sync across the app. 
``` js
import { useSettings } from '../context/SettingsContext'
/* later in the component */
const settings = useSettings() // e.g. { unit: "sats", showBalance: false }
<p>Unit: {settings.unit}</p> // read settings; when they change this component will be re-rendered
```
``` js
import { useSettingsDispatch } from '../context/SettingsContext'
/* later in the component */
const settingsDispatch = …
```
=> feat: add settings screen

src/context/SettingsContext.jsx
Always take default values into account when initializing the settings for the first time, as it might already contain some values (e.g. from `prefers-color-scheme` handling)
Fixes #32.
=> fix: initialize local storage with default values

docker/regtest/readme.md
Minor typo fixes and an update for the rebuild command: I had to use the `--no-cache` option to get the current latest master version of JoinMarket, without it it was using the previous, cached version of their master.
=> docs: Docker README improvements

src/components/CreateWallet.jsx
There are some pros and cons for password auto-completion, however on the create wallet page it should propably not prefill with an existing password - what do you think? 
Most modern browsers will optionally open a dialog to choose from.
Before:
After:
See [info about autocomplete attribute and login fields from Mozilla](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields)
=> feat: do not autocomplete password when creating wallet

src/components/Navbar.jsx, src/components/Sprite.jsx, src/index.css
Changes the mobile version of the navbar from a [collapse](https://getbootstrap.com/docs/5.0/components/collapse/) to an [offcanvas](https://getbootstrap.com/docs/5.0/components/offcanvas/) drawer.
It would be nice to show the offcanvas drawer under the navbar somehow but I couldn't find a good way of doing that (except maybe hardcoding a margin but not sure how good that would be).
=> fix: change navbar collapse to offcanvas

src/components/Navbar.jsx, src/index.css
Fixes inconsistent padding in the navbar which caused ugly jumping effects when switching from the non-active to the active state of the wallet preview in the navbar.
🎥 **Before:**
🎥 **After:**
=> fix: navbar padding

src/components/DisplayAccounts.jsx
Quick fix to display the correct amount per address.
Small bug seems to have been introduced while refactoring that will led to the balance of addresses always end up displaying the whole account balance.
=> fix: display amount of addresses correctly

src/index.css
=> fix: brighten loading indicator in dark theme

src/components/Balance.jsx
Properly centers the "hidden" icon and size it relative to the current active font size.
This is important for when balances are shown in larger font such as in the "privacy level screen" in #51.
=> fix: hidden balance icon alignment and size

src/components/App.jsx
As talked about in issue #28 I added a connection indicator to the footer. It is a simple 'Connected' or 'Disconnected' message with a red or green dot beside it. It uses the state `connectionError` as a conditional.
Here is how it looks:
I can make changes if anyone has any feedback.
Thanks
Closes #28
=> feat: add connection indicator to footer

src/components/App.jsx
Fixes a small warning  "Invalid DOM property `class`. Did you mean `className`?".
For anyone also wondering why a warning is given even when resulting DOM is exactly the same: https://www.geeksforgeeks.org/why-react-uses-classname-over-class-attribute/
=> fix: Invalid DOM property 'class' in App

src/components/App.jsx, src/components/CreateWallet.jsx, src/components/CurrentWalletAdvanced.jsx, src/components/CurrentWalletMagic.jsx, src/components/Earn.jsx, src/components/Receive.jsx, src/components/Send.jsx, src/components/Wallet.jsx, src/components/Wallets.jsx, src/libs/JmWalletApi.js
This change really just moves all `fetch` calls to a single file `libs/JmWalletApi.js`.
It does not aim to be feature-complete, nor does it add any feature, increase configurability or something else.
So this can definitely be improved in the future, but is out of scope for now.
I'd need feedback on the method naming (e.g. just `walletAddressNew`) and params, as I did not include `signal` param in every call (because it has not been used in specific requests) and conversion between `name` and `walletname` feels also a bit cumbersome.
Closes #60
=> refactor: collect api requests in single file

src/components/CreateWallet.jsx, src/index.css
Resolves #65.
I've made it so that the user needs to reveal the sensitive info at least once for the "Fund wallet" button to become active.
=> feat: hide sensitive info on wallet create

src/components/App.jsx
Navigates to "/" on unmapped paths, e.g. `/unmapped`, `/this-is-a-path-that-leads-nowhere`, but also on `/send`, `/earn`, etc if no wallet is active.
Closes #81
=> fix: navigate to root on unmapped path

src/components/App.jsx, src/components/Onboarding.jsx
There were several warnings originating from two causes:
```
./src/components/App.jsx
Line 93:12:   'React' must be in scope when using JSX  react/react-in-jsx-scope
```
Fix: Import `React` in `App.jsx`
```
./src/components/App.jsx
./src/components/Onboarding.jsx
Line 187:17:  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank
```
Fix: Add `noopener` to all links with `target="_blank"`
=> fix warnings during build

src/components/CreateWallet.jsx
Noticed this during testing the docker setup. 
The checked `name` property is actually from the function `createWallet` rather than the reference to variable `createdWallet`.
Seems to invoke an error in the packaged application but does not show up during development.
=> fix: condition check during wallet confirmation

src/libs/JmWalletApi.js, src/setupProxy.js
A reverse proxy must be used in order to use this application. Since such a proxy might want to enforce it's own authentication mechanism, a small adaption is needed how requests to `jmwalletd` are constructed and forwarded.
This change includes sending the bearer token via a header named `x-jm-authorization` instead of `Authorization` in order for the reverse proxy to use the `Authorization` header for it's own purposes.
From this change onward, any reverse proxy that wants to deliver this application must forward the  `x-jm-authorization` header as `Authorization` header to `jmwalletd`. No other changes are needed for the development environment.
=> feat: ability for reverse proxy to enforce own auth scheme

public/index.html
With this change the `site.webmanifest` file can be fetched on a server with an auth mechanism enabled.
From [developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin#example_webmanifest_with_credentials):
> The use-credentials value must be used when fetching a [manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest) that requires credentials, even if the file is from the same origin.
For more on why this is needed on `rel="manifest"` see [here](https://github.com/w3c/manifest/issues/535#issuecomment-435739223).
=> fix: enable fetching manifest with credentials

src/components/CurrentWalletMagic.jsx
Let's the user hide the balance by clicking on it on the main wallet screen.
Initially, the balance is hidden. Having to go to the settings screen to show it might be a bit cumbersome. Clicking on the balance (on the main wallet page only) lets the user reveal the balance more easily. This is also what the [bitcoin design guidelines](https://bitcoin.design/guide/onboarding/protecting-a-wallet/#quickly-hiding-balances) recommend.
https://user-images.githubusercontent.com/10026790/154489584-23bddf00-acb1-4cf7-9d3f-284482f3ec39.mov
=> feat: make balance hideable on click

src/components/App.jsx, src/components/PageTitle.jsx, src/components/Wallet.jsx, src/components/Wallets.jsx
More consistence in regards to other pages.
- Use one row and col for the whole page
- Alert not using full width anymore
- Slightly increased "Create new wallet" button when no wallet exists.
- The `PageTitle` is not centered anymore, which deviates from the Figma screen.
Personally, I think it looks better to have the headlines all in the same place (e.g. switching to the "Create Wallet" screen and back seemed a little awkward before) What do you think?
Before/After without wallets:
Before/After with wallets:
=> feat: update wallets page

src/components/DisplayAccountUTXOs.jsx, src/components/DisplayAccounts.jsx, src/components/DisplayUTXOs.jsx, src/libs/JmWalletApi.js
I didn't want to cheat a feature in before the next version. I was just fixing the display in dark mode... and I thought... why not?
I'm happy to just fix the visual defect if you want. However, this would at least provide a proper workaround for users just trying things or testing to recover when they mistakenly sent to an address twice.
Before/After UTXO:
Before/After Accounts:
=> feat: freeze/unfreeze utxos and fix style on dark theme

.npmrc, RELEASING.md, package.json, scripts/changelog.mjs
Resolves #105.
Building on the feedback in #103, this integrates `npm version` into the release process.
Now, when you run e.g. `npm version patch`, it will:
1. Bump the version
2. Update the changelog
3. Commit the changes to a branch
4. Push the branch and open a _draft_ PR. (Let me know if we should add a manual step in between here.)
See the new RELEASING.md for more details.
This is just a suggestion. My main goal is to make everything as painless and automated as possible while sticking close to npm tooling. Please let me know what you think of it and what we could do better!
=> devtools: document and further automate release process

src/components/Send.jsx, src/libs/JmWalletApi.js
Closes #101 
This PR fetches the `minimum_makers` config variable and uses it as minimum amount of collaborators on the Send page.
This means a taker operation cannot be started with a lower value than what is specified in the config file.
One little caveat is that the initial value for the amount collaborators is randomized between `[5, 7]` (min +1, min +3), which can lead to the initial value not being shown as active button in the `CollaboratorsSelector` component. 
Is this acceptable for now? What do you think?
<br />
<br />
Screenshot for `minimum_makers := 2`:
<br />
Also, the approach of parsing an error message from `text/html` is removed as this has been fixed in [joinmarket-clientserver#1170](https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1170)
Edit: this also …
=> Take minimum_makers config var value into account on Send page

src/components/Wallet.jsx, src/components/Wallets.jsx
Resolves #43.
Fixes two inaccuracies where a component's state was set after it was not mounted anymore.
<details>
<summary>Click for original error messages</summary>
<p><code>
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
Wallet@http://localhost:3000/main.b9362308f6a079a3bad2.hot-update.js:50:7
div
./node_modules/react-bootstrap/esm/Col.js/Col<@http://localhost:3000/static/js/bundle.js:25391:14
div
./node_modules/react-bootstrap/esm/Row.js/Row<@http://localhost:3000/static/js/bundle.js:27416:7
Wallets@http://localhost:3000/static/js/bundle.js:6638:7
</code></p>
<p><code>
Warning: Can't perform a React state …
=> fix: set state on mounted component only

src/components/App.jsx, src/components/CreateWallet.jsx, src/components/CurrentWalletAdvanced.jsx, src/components/CurrentWalletMagic.jsx, src/components/Earn.jsx, src/components/Layout.jsx, src/components/Receive.jsx, src/components/Send.jsx, src/components/Settings.jsx, src/components/Wallets.jsx
Resloves #107.
Moves the repetitive 
``` html
<Row>
<Col md={10} lg={8} xl={6}>
</Col>
</Row>
```
we had on almost every page and raises it up to the `App.jsx` level:
``` html
<Routes>
<Route element={<Layout />}>
<Route path="/" element={<Wallets />} />
<Route path="create-wallet" element={<CreateWallet />}
</Route>
</Routes>
```
Unfortunately, Git doesn't detect the changes well so it looks like a lot of changes when in reality its just removing the wrapping `Row` and `Col` tags from all the pages.
=> refactor: dry up app layout

public/index.html, src/components/Sprite.jsx, src/index.jsx, src/libs/JmWalletApi.js
Right now the only way to deploy the web UI is with a separate host, it does not work in a subdirectory/path like `/joinmarket/`. I came across this trying to integrate the Web UI into the BTCPay Server setup. We want to avoid the complexity of setting up different hosts (and SSL certs) per service, that's why we deploy services in paths under the main domain.  
This PR determines the deployment base path depending on whether `PUBLIC_URL` is set. We aren't making use of the [`PUBLIC_URL` environment variable](https://create-react-app.dev/docs/adding-custom-environment-variables/#referencing-environment-variables-in-the-html), which is perfectly fine as it would require us to set it on build time and different integrations might want to use different paths anyways. 
I've tested this …
=> feat: allow for deployment in subdirectory

docker/regtest/docker-compose.yml, docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile, src/components/App.jsx, src/components/Earn.jsx, src/components/Send.jsx, src/context/WebsocketContext.jsx, src/index.jsx, src/setupProxy.js
This PR reintroduces the websocket connection to the backend. Closes #46.
The backend listens on port 28283 for incoming websocket connections.
See the [jmwalletd websocket documentation](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/v0.9.5/docs/JSON-RPC-API-using-jmwalletd.md#websocket).
A reverse proxy must pass all incoming connections with path `/jmws` to the backend server.
`/jmws` was chosen, as `/ws` is used by [`WebpackDevServer` by default](https://github.com/facebook/create-react-app/blob/v5.0.0/packages/react-dev-utils/webpackHotDevClient.js#L66). We could change that, but having it on a different path has some benefits.
The websocket connection, as it is currently implemented, is responsible for two things:
- Updating the maker/taker state
- Updating the …
=> feat: readd websocket connection

src/components/App.jsx
Tiny, tiny, tiny change..: Add bottom spacing to the onboarding screen:
Before:
After:
=> fix: add bottom spacing to onboarding screen

README.md
Raspiblitz fixes [^1][^2] are now merged and can be fetched by running `patch`. After that, the install will work.
[^1]: https://github.com/rootzoll/raspiblitz/pull/2987
[^2]: https://github.com/rootzoll/raspiblitz/pull/2988
=> docs: update raspiblitz install instructions

docker/regtest/common.sh, docker/regtest/dockerfile-deps/joinmarket/latest/docker-entrypoint.sh, docker/regtest/fund-wallet.sh, docker/regtest/init-setup.sh, docker/regtest/mine-block.sh
Closes #138 
User had `jq` not installed - this changed will print a more informative message if any dependency is missing.
Current dependencies of the development setup are `jq`, `curl` and `docker`.
If any of them is missing it will print , e.g. 
```sh
[user@home regtest]$ ./init-setup.sh 
This script needs 'curl' to run. Consider installing it.
```
Edit: Also fixes some shellcheck warnings - just minor warnings of [`SC2015`](https://github.com/koalaman/shellcheck/wiki/SC2015) left, which are intended ("Ignore this warning when you actually do intend to run C when either A or B fails.")
=> chore: check for dependencies in dev setup scripts

package-lock.json, package.json, src/components/BitcoinQR.jsx, src/components/Receive.jsx, src/index.css, src/index.jsx
Closes #145.
Problem was that the library [bitcoin-react](https://github.com/IsmaelTerreno/bitcoin-react) always adds parameters to the uri, even when they are not defined (and will happily include them as `x=undefined`). Some wallets seem to have problems with that. 
This PR replaces the external library with a simpler internal component that will only ever output
- `bitcoin:{address}` or
- `bitcoin:{address}?amount={amount}`
Also: Removing external dependencies is good (only `bitcoin-react` is removed, `qrcode` still needed of course).
Also: Sats the standard.
=> fix: use own qrcode component to display addresses

src/components/Earn.jsx, src/components/Send.jsx
Closes #135.
This is really just a workaround for users connecting Jam to existing backends.
This will never happen in our integrations like Umbrel, as we predefine max fee values.
Additional requests to check for existing max fee values are only made if the taker operation reported the error `Action cannot be performed, config vars are not set.`.
I did not find a good place to make the check and opted to do it just after the original error happens. If we check for more things like that it might be good to do that on initial application start, but I refrained from doing so for this uncommon case for now. Feedback on how to make it more clear/readable is highly appreciated.
=> Warn on missing config vars

src/components/Send.jsx
Resolves #134.
Updates the suggested number of collaborators to be 8-10 or higher. This is the actual default value, not 5-7 like we had previously.
=> fix: update suggested number of collaborators

src/components/App.jsx, src/components/CurrentWalletAdvanced.jsx, src/components/CurrentWalletMagic.jsx, src/components/Receive.jsx, src/components/Send.jsx, src/context/WalletContext.jsx
Closes #161 .
This PR adapts the wallet initialization.
Before these changes, the `currentWallet` was initialized with `null` and subsequently updated with the values of a session object in an `useEffect` callback. This causes the route setup for components that need a loaded wallet to redirect to `/` on a page refresh, because they are conditionally added with `{currentWallet && (<Route element= [...] />)}`) and `currentWallet` is always `null` on initial rendering.
After these changes, the `currentWallet` will be initialized directly from the session object, if available.
If no session is available, the behaviour stays the same - it will redirect to `/`. However, if a session is available, it will be able to reload the page normally.
I was not sure at first if some components depend on …
=> Fix page reloads

src/components/CurrentWalletMagic.jsx
As discussed in yesterday's call, un-reverses the mixdepth ordering.
=> fix: change misdepth order

src/components/Receive.jsx
resolves #159 
I tested this in brave, safari, and firefox using an http tunnel with [ngrok](https://ngrok.com/), which should be similar to the app running in umbrel
While working on this I discovered that `document.execCommand` is deprecated, but still has good browser support, and  [umbrel is using the same pattern for it's copy behavior](https://github.com/getumbrel/umbrel-dashboard/blob/master/src/components/Utility/InputCopy.vue#L74).
I tried to avoid using `position: absolute` and instead making an inline invisible input but `inputRef.current.select()` doesn't work properly with that, and just selects an empty string. 
Really excited about this joinmarket webui project and hope to contribute more in the future!
=> fix: receive address copy button not working

src/components/Balance.jsx, src/components/Balance.test.jsx, src/components/CurrentWalletMagic.jsx, src/components/DisplayAccounts.jsx, src/components/DisplayUTXOs.jsx, src/components/Navbar.jsx, src/index.css
Uses satscomma-style [^1][^2][^3] formatting for the fractional part of a bitcoin balance. As mentioned in the last community call, this will make it way easier to parse the amount of sats in a balance displayed in bitcoin. Decided to go with a half-space as the digit group separator. Looks the cleanest imo. Also did some minor refactoring of the `Balance` component itself.
[^1]: https://bitcoin.design/guide/payments/units-and-symbols/#satcomma
[^2]: https://medium.com/@mark.nugent.iv/grouping-bitcoins-fractional-digits-an-idea-whose-time-has-come-22d9dad8ac51
[^3]: https://medium.com/coinmonks/the-satcomma-standard-89f1e7c2aede
=> feat: satscomma formatting for bitcoin balances

src/components/DisplayAccountUTXOs.jsx, src/i18n/locales/en/translation.json
Typo:
- in translation: "connecction" => "connection"
- in translation key: "acount" => "account"
=> chore: fix typo in en/translation.json

docker/regtest/docker-compose.yml, docker/regtest/readme.md, package.json
Small cleanups and improvements for the regtest environment:
- remove custom `gaplimit` in jm containers (as it is not really needed and we should aim at using defaults wherever it is possible)
- remove unused tor config in primary jm container (left unchanged for secondary container)
- reorder container definitions according to their "importance" (e.g. jm containers first)
- add npm scripts to interact with regtest env
e.g. when you want to use the latest update for the regtest environment, instead of
```sh
docker-compose -f ./docker/regtest/docker-compose.yml build --pull --no-cache
```
you can now just execute:
```sh
npm run regtest:rebuild
```
=> Update regtest env

src/components/DisplayUTXOs.jsx, src/components/Send.jsx
Fixes an error introduced by me while porting the api to typescript.
Request body should contain `mixdepth` as property, not `account`.
=> fix: pass correct request body in send-direct request

src/components/App.jsx, src/components/CreateWallet.css, src/components/CreateWallet.jsx, src/components/CreateWallet.test.jsx, src/components/Seedphrase.css, src/components/Seedphrase.jsx, src/index.css
Closes #196 
Unfortunately, for now it wont protect from clicking a link inside the app, ie. the Jam logo
One problem still needs to be addressed: In case the wallet was successfully created, but the backend goes down (for whatever reason), the whole screen is replaced by a "No connection" error message. This should be prevented when `CreateWallet` component is active. It is partly tracked in #149 and covered in #199
=> Remove skip button quiz screen

.github/workflows/build.yml, .npmrc, package.json
Add `engine-strict` to `.npmrc` to enforce minimum npm and node version specified in section `engines` of `package.json`.
Thereby also updating the minimum npm version from `v7.0.0` to `v8.0.0` and node from `v16.0.0` to `v16.11.0`. This is to prevent annoying diffs to `package-lock.json` when installing new packages.
If you try to execute `npm install` with an unsupported version, you will now get the following message indicating you to update your setup, e.g. with `npm install npm -g` and `nvm install --lts` (in case you are using `nvm`):
```sh
[user@home joinmarket-webui]$ npm i
npm i
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: jam@0.0.5
npm ERR! notsup Not compatible with your version of node/npm: jam@0.0.5 …
```
=> dev: enable npm config `engine-strict`

src/components/Send.jsx, src/i18n/locales/en/translation.json
Tiny, tiny PR to get item "Improve wording of error message when trying to send to an 'invalid' address" off the list #66
When sending non-collaborative transactions with an invalid recipient, the api responds with `400 Bad Request` and an error message of `Invalid request format`. 
`InvalidRequestFormat` error is thrown on all assertion errors.. see [wallep_rpc.py#L548](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/fd5871bb2d89e96efe344040b4576627e84fc644/jmclient/jmclient/wallet_rpc.py#L548), but  `Invalid request format` is not really useful for the user and it might not be clear what to do.
As this is an ubiquitous error message, and address validation is avoided on the client side, to give at least a hint about what might be wrong, the message is appended with …
=> ui: enhance error message on bad request errors

src/components/App.jsx, src/components/CreateWallet.jsx, src/components/DisplayUTXOs.jsx, src/components/Earn.jsx, src/components/Send.jsx, src/components/Wallet.jsx, src/context/ServiceInfoContext.tsx, src/context/WalletContext.tsx, src/libs/JmWalletApi.ts
Closes #149, ie. do not navigate away when a user is in the process of writing down the seed.
Additional changes:
- refactor: always extract api error message with Api.Helper
- refactor: port WalletContext from jsx to tsx
- remove 'exact' property as it is not available in react-router v6 anymore
=> fix: do not hide CreateWallet component on connection errors

src/context/WebsocketContext.jsx
This commits force-closes pending websocket connections after a certain duration.
Tested in Firefox and Chrome-based browsers, and only happens in Firefox after around ~12 attempts.
A new constant `WEBSOCKET_ESTABLISH_CONNECTION_MAX_DURATION` is defined (`10_000` ms),
after which a pending connection will be closed.
Comment from the code on why this is needed:
```
// Problem:
//   Some browsers will keep connecting longer than the retry delay, and if the service
//   comes back up in the meantime, the connection fails nonetheless...
//   A retry is only attempted, when the close listener is invoked.
//
// Solution:
//   If the socket is still `CONNECTING` after a certain duration.. force-close it!
//   e.g. this happens in Firefox after >10 attempts
//
// This ensures that the maximum …
```
=> fix: force-close pending websockets connections

src/context/WebsocketContext.jsx
Firefox throws a `DOMException` when using `1001` as close code: `A parameter or an operation is not supported by the underlying object`.
Cannot really find out why this is, but in this case it does not really matter, as the code only runs if there is no connection in the first place.
=> fix: use `1000` as websocket close code

public/sprite.svg, src/components/Balance.jsx, src/components/Balance.test.jsx, src/components/CurrentWalletMagic.jsx, src/components/CurrentWalletMagic.module.css, src/components/Navbar.jsx, src/components/Receive.jsx, src/components/Receive.module.css, src/components/Send.css, src/components/Send.jsx
Some small stuff that has been noticed after #203 has been merged.
- add border-radius to input field placeholder
- align loading spinner in submit buttons on `Send` and `Receive` screen
- re-add initial collaborative transaction toggle state on Send screen
- restore send form field order ("account to send from" is at the top)
- avoid flickering on receive page (still not sure if the placeholder for the qr code should be displayed, when an address is already present; there is a case for showing it just for the initial loading phase)
- re-add icons on send/receive buttons in `CurrentWalletMagic`
Findings: When the initial page load is the `Send` page, the "collaborative transaction" toggle is not enabled - this should be fixed after is #218 rebased. 
Edit: Uff.. these placeholders are …
=> ui: small visual adaptions after placeholder PR

CONTRIBUTING.md
The link on the contributing page points to a 404 page:
https://github.com/joinmarket-webui/joinmarket-webui/blob/master/CONTRIBUTING.md
=> fix: link to dev docs on contributing page

src/components/App.test.jsx, src/components/CreateWallet.test.jsx, src/components/Earn.jsx, src/components/Earn.module.css, src/components/Wallet.test.jsx, src/components/Wallets.jsx, src/components/Wallets.test.jsx
Closes #225.
Reloads the session information on `Earn` and `Wallets` screens.
Additional change: In order to mitigate a problem when the maker is started/stopped too quickly in succession, the "submit" button is re-enabled with a time delay (currently 2 seconds). This behaviour feels a bit strange, but I think it's still better than the service not working at all – feedback on that is welcome.
=> reload session info on Earn and Wallets screen

src/components/Earn.jsx
Uses Formik for form validation on Earn screen.
Further adaptions: 
- Don't persist form values to local storage on every update, but just when the form is actually submitted
- Separate info and error alert - those are not mutually exclusive
=> refactor: use Formik on Earn screen

src/components/Send.jsx
Closes #187.
Main goal of these changes: Users should see the correct balance after a send.
Before this PR, the send page contained outdated information after submitting the form, as relevant information is only loaded once. After this PR, the relevant information is reloaded and the correct balance is shown.
In order to know if the balance is synchronized, it must be waited till the spent utxos are removed from the wallet's utxo set.
This can be done for "direct sends", but not for collaborative transactions.
So the approach is different for both
- after direct-send, wait for wallet's utxo set to be synchronized, then reload data
- after starting taker operation, wait for it to finish, then reload data
=> Reload wallet data after send 

src/components/Earn.jsx, src/components/EarnReport.jsx, src/components/EarnReport.module.css, src/components/EarnReport.tsx, src/i18n/locales/en/translation.json
Currently, the report is rendered directly on the Earn screen and is limited by the container width. This makes it cumbersome to read. This change will render the report in an overlay spanning the whole screen.
The report can generally be improved quite massively in the future. While this might be a very easy win, it is out of scope for this PR. All this change is doing is creating a better view of what was already present.
=> refactor: Report overlay

src/components/Jam.jsx
Closes #250 
Prevent executing submit action of Scheduler form while data is still loading.
Was already "kind of" prevented by disabling the button (https://github.com/joinmarket-webui/joinmarket-webui/blob/master/src/components/Jam.jsx#L333). Now also enforced before making the request.
=> fix: prevent starting/stopping scheduler while data is loading

src/components/Jam.jsx
`err.response` is only populated by actual `JmApiErrors`, it might be `undefined`.
e.g. on aborts (`signal.aborted := true`)
This can be reproduced by artificially limiting your network connection speed, e.g. via Dev Tools (most browser should be able of doing that, I suppose).
=> fix: possible reference error in catch clause

src/components/Send.module.css, src/index.css
Remove catch all css rule overriding all border colors in dark mode.
Some bootstrap elements apply `border-color: transparent` to elements for a reason, e.g. buttons without borders.
These rules are overwritten by the custom rule included in `index.css`
```css
:root[data-theme='dark'] * {
border-color: var(--bs-gray-800) !important;
}
```
It has happened more than once now that this rule gets in the way rather than being helpful.
A benefit of this change is that elements are easier to use and more consistent across themes.
A drawback is that all new elements must take the border color into account.
Also, visual effects on the elements when removing the catch all rule:
- Border color of input fields on validation (works in light mode)
- valid input fields get a green border
- invalid input …
=> refactor: remove catch all style rule for border-color in dark mode

src/components/Jam.jsx, src/libs/JmWalletApi.ts
Resolves #249.
I used the same delay (2000ms) as in the Earn screen. What do you think @theborakompanioni, is that long enough?
A bit off topic, but I also renamed all API methods to refer to "Scheduler" now.
=> fix: delay scheduler start/stop

src/components/Balance.jsx, src/components/Balance.test.jsx, src/components/CurrentWalletMagic.jsx, src/components/Navbar.jsx
Adds the ability to toggle balances if they are hidden by settings.
Visible balances cannot be hidden (by default).
As a user, I want to quickly see a balance and not navigate to the settings for that.
There is a toggle on the magic wallet page, but it is needed in other places too (e.g. new Jam page, wallet page in advanced mode, etc.). In addition, this toggle mechanism is per displayed balance - it does not touch the settings values.
It was annoying for me sometimes, hence the PR – but that does not mean this should get merged right away. Let me know what you think.
=> feat: Individual balance toggle

src/index.css
It feels that the placeholders in light mode are little bit too bright. On some screens it is hard to tell the difference from the background. Do you think it would be an improvement if they were a little darker?
Just for reference, this would be the original Bootstrap style (applying `currentColor`):
=> ui: decrease brightness of placeholder in light theme

src/components/Send.jsx, src/i18n/locales/en/translation.json
As the title says: Send button signals non-privacy payment choice as suggested in Figma.
edit: Images are outdated – instead of "Normal Send – …", it just says "Send – …".
=> ui: big red button for payments without improved privacy

src/components/App.jsx
Bottom right, next to GitHub link. Link will lead to /tags.
Won't be shown on small screens.
=> feat(footer): show Jam version

src/components/Jam.jsx
Resolves #282.
Splits up the internal destination addresses of the scheduler over 3 mixdepths. This is to make it harder for a consolidation to happen later on (e.g. imagine all 3 UTXOs on one mixdepth and the user then sweeping this mixdepth).
=> feat: split up scheduler destiantion addresses over 3 mixdepths

src/components/App.jsx, src/components/Cheatsheet.tsx, src/constants/features.ts, src/i18n/locales/en/translation.json
Removes cheatsheet from feature flags, thereby enabling it for everyone.
Also fixed the link to the Jam page.
Did **not** change the order of the entries. But that can be done quickly. Thoughts?
=> chore: enable cheatsheet

src/components/App.jsx
Decrease the vertical padding on mobile screens from `py-5` to `py-3`.
=> fix: less vertical padding of main container on mobile screens

src/components/Cheatsheet.module.css, src/components/Cheatsheet.tsx, src/i18n/locales/en/translation.json, src/index.css
Closes #290 (?)
Changed:
- Use "tick" as last item in the list
- Re-add link to Send screen
- Move cheatsheet styles to own module
- Add `box-shadow` style to cheatsheet overlay
Not changed:
- The figma designs has other wordings than chosen in https://github.com/joinmarket-webui/joinmarket-webui/pull/211#issuecomment-1096706454 . This wording has not been changed.
Let me know if this is okay for you @editwentyone!
(Screenshots slightly outdated: aligned numbered items to start position, as it was before)
=> ui: cheatsheet optimization

src/components/CreateWallet.jsx, src/i18n/locales/en/translation.json
Closes #294.
Adds the following phrase to the `CreateWallet` screen:
> "Please be patient, this may take a few minutes."
=> ui: add hint about creating wallet duration

src/context/WalletContext.tsx, src/libs/JmWalletApi.ts
This fix prevents unnecessary wallet info requests.
Wallet data is automatically loaded on initial page renderings automatically.
However, if a components needs an up-to-date balance, it always triggers `reloadCurrentWalletInfo`.
Before this commit, this meant that the data is loaded twice when the app is refreshed on a component that needs wallet infos.
After this commit, the `reloadCurrentWalletInfo` method knows that an api request is already performed and will wait for it to be completed.
Before:
After:
=> fix: prevent unnecessary wallet info requests

src/components/Send.jsx, src/context/ServiceConfigContext.tsx, src/context/WalletContext.tsx, src/index.tsx, src/testUtils.tsx
Closes #279 
Before: Config values were fetched individually on every send page.
After: Config values will be loaded only once, then stored and reused for the entire wallet session.
Only the `Send` component currently needs a config value for form validation (`minimum_makers`).
Others are loaded conditionally in case of an error (`max_cj_fee_rel` and `max_cj_fee_abs`)).
There are also other potential worthwhile solutions.. this seems to be a very straightforward one. Let me know, what you think.
The config update are logged to console in development mode:
```js
service config updated Object { 
POLICY: Object { minimum_makers: "1",  max_cj_fee_rel: "0.0003", max_cj_fee_abs: "300000" }
​​}
```
=> Fetch config values only once per wallet session

docker/regtest/readme.md
Small adaptions in local dev setup readme. 
The docs now include the local dev wallet name and password that is created by the init script.
=> docs: update dev setup readme

src/components/Earn.jsx
Before this commit, only the "developer mode" had the ability to open the earn report.
After this commit, the earn report button will always be shown, hence enabling it for all users by default.
=> feat: enable report overlay

src/components/Navbar.jsx, src/index.css
Adds dividers between the main tabs to hint towards the expected flow a user should/could take.
Trade off is that the tabs won't be of equal length anymore but that is ok imo.
Side note: Eventually we need an "official" color palette. Right now we're mixing colors from bootstrap and Figma screens.
=> ui: tab dividers

src/components/CurrentWalletMagic.jsx, src/components/Jars.jsx, src/i18n/locales/en/translation.json
Resolves #343.
Adds a shortcut for receiving by clicking on jar 0 when it's empty. Only applies to jar 0 -- we don't want to encourage receiving on other jars.
<table>
<tr>
<th>Empty</th>
<th>Non-empty</th>
</tr>
<tr>
<td><img width="133" alt="Screenshot 2022-06-21 at 12 34 37" src="https://user-images.githubusercontent.com/10026790/174779854-afd98a56-5086-470c-9a3f-524dfc4793cb.png"></td>
<td><img width="158" alt="Screenshot 2022-06-21 at 12 34 08" src="https://user-images.githubusercontent.com/10026790/174779845-d87f99aa-bd08-4bfd-b990-616bfeb6c883.png"></td>
</tr>
</table>
=> feat(jars): add receive shortcut if jar 0 is empty

src/components/CreateWallet.jsx, src/components/Wallet.jsx, src/components/Wallets.jsx
Small changes in `Wallets`, `Wallet` and `CreateWallet`:
- Simplify handling in `Wallets` components – code "should" be a little bit more readable
- Do not use hardcoded link to `/wallet` string in `Wallet` and `CreateWallet`: use values from global `routes`
=> chore: Use `routes` where applicable

src/components/CreateWallet.jsx, src/components/Jam.jsx, src/components/Send.jsx, src/components/Settings.jsx, src/components/ToggleSwitch.tsx, src/components/fidelity_bond/FidelityBondDetailsSetupForm.tsx
Fixes #309.
Small change to control the `checked` value by the parent component.
Previously a state change in the calling component was not visually displayed by the `ToggleSwitch` component.
After this change the `ToggleSwitch` will reflect the actual value correctly.
=> fix: checked state of ToggleSwitch can be controlled by caller

src/components/Receive.jsx, src/components/Receive.module.css, src/i18n/locales/en/translation.json, src/i18n/locales/fr/translation.json
Closes #328.
Not changed / Differences to [Figma](https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=2850%3A71544) screen:
- Balance is shown directly beneath jars (using the `SelectableJar` component)
- No simple/advanced view toggle on top of page:
- Jars are displayed in the "Advanced dropdown" section
- Q: This is still shown in "advanced mode" only (Must be enabled on the Settings page).. Refrained from always showing it since this might encourage directly funding other jars: Okay for now?
=> feat(jars): destination jar selector on receive screen

public/sprite.svg, src/components/Receive.jsx, src/components/Receive.module.css
Small adaptions to align the Receive screen with [Figma](https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=2850%3A71544) designs.
Changes:
- Style submit button according to Figma
- display "refresh" icon in front of the text
- Button does not take the whole width
- show sat symbol on `amount` input (not in Figma, but also used on Earn screen)
Not changed:
- The button text in Figma says "Create new address" – "Get new address" feels more appropriate, does it?
=> ui: Receive screen advances

src/components/Jam.jsx, src/components/Send.jsx, src/hooks/CoinjoinPrecondition.test.tsx, src/hooks/CoinjoinPrecondition.ts, src/i18n/locales/en/translation.json
Closes #155.
Before this commit, the `Send` page did not validate minimal preconditions that must be met before executing a collaborative transaction. Only the `Jam` page (invoking the scheduler, hence multiple collaborative transactions) displays a warning with further information.
In this commit, the minimal preconditions currently in place (min. 1 spendable utxo [not frozen, not timelocked], min. 5 confirmations of at least one utxo, at least 1 retry left) are externalized to `hooks/CoinjoinPrecondition.tsx`. These prerequisites are currently not very well verified and tested, and can probably be improved a lot – this _is not part_ of this PR.
After this commit these preconditions are also used on the `Send` page when a collaborative transaction is attempted, and if not met, a warning …
=> fix: Check preconditions before send request

src/components/App.jsx, src/components/Settings.jsx, src/components/Wallet.jsx, src/components/Wallet.test.jsx, src/components/Wallets.jsx, src/components/Wallets.test.jsx
Refactoring for easier testing and in preparation of https://github.com/joinmarket-webui/joinmarket-webui/pull/334, enables reacting to "lock/unlock" attempts in `Wallets` component.  
Instead of passing `startWallet` and `stopWallet` to the `Wallet` component, this will perform the API requests in the parent `Wallets` component and just provide `unlockWallet` and `lockWallet` callbacks to the child.
This in turn greatly simplifies the `Wallet` component: Instead of passing multiple properties to determine whether "lock" and "unlock" buttons should be shown, this decision is made by the caller. 
No functionality has been added or removed.
=> refactor: move lock/unlock requests from `Wallet` to `Wallets`

src/components/jars/Jar.module.css
`min-width` for jar balances as suggested in https://github.com/joinmarket-webui/joinmarket-webui/pull/357#issuecomment-1169699489.
Approve: It's better than before.
Decline/Close: It's worse.
=> ui: min-width for jar balances

src/components/fb/CreateFidelityBond.jsx
Pass main content of Fidelity Bond's confirm modal as child node instead of `body` param.
=> fix: pass body of confirm modal via child node

src/components/DisplayUTXOs.jsx, src/components/fb/FidelityBondSteps.tsx, src/components/fb/utils.test.ts, src/components/fb/utils.ts, src/hooks/BalanceSummary.test.tsx, src/hooks/BalanceSummary.ts, src/hooks/CoinjoinPrecondition.ts
Resolves #373.
Small refactoring: Move function `isLocked` to check expiry date of timelocked utxo to proper place from `BalanceSummary` to `fb/utils`.
=> fix: Expired fidelity bonds are still shown as locked in UTXO selector

src/components/Earn.jsx, src/components/fb/CreateFidelityBond.jsx
Resolves #363.
Reloads the fidelity bond UTXOs on the earn page after crating a new fidelity bond so that they show up without the user needing to refresh the page.
=> fix: reload utxos after creating a fidelity bond

src/components/Earn.jsx
Creating a fidelity bond funding transaction includes freezing utxos, which should not be done when a taker or maker is running.
Before this commit, the FB form is hidden when the taker service is running, but not when the maker is running. 
After this commit the form is hidden when any service is running, while still displaying existing FBs when the maker is active).
=> fix: do not show FB create form when maker is running

src/libs/JmWalletApi.ts
Resolves https://github.com/joinmarket-webui/joinmarket-webui/issues/387.
Quickfix for the issue by encoding the wallet name in the url path.
An alternative solution would be prevent certain characters as proposed in https://github.com/joinmarket-webui/joinmarket-webui/issues/352. Nonetheless, if other chars than [a-zA-Z0-9] are allowed, it would have to be escaped anyway.
=> fix: encode wallet name param in url path

src/i18n/locales/en/translation.json
For now we're limited to starting the scheduler from Jar #0 at least until https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1260 is released server-side.
Since this can be confusing, let's at least mention it to the user. See also https://github.com/joinmarket-webui/joinmarket-webui/issues/391.
=> fix: mention jar #0 in preconditions

CONTRIBUTING.md
As reported in the support chat, this replaces `docker-compose` commands with their `npm` equivalents in CONTRIBUTING.md.
=> docs: update regtest commands in CONTRIBUTING.md

src/components/Send.jsx
Fixes the background color of the custom collaborative selector input in dark mode.
Problem was that the name of the css class has not been applied properly.
Edit: Misleading branch name.. wanted to fix something else. Please ignore.
=> fix: color of selected collaborators-selector-input

src/components/Send.jsx, src/i18n/locales/en/translation.json
Resolves #404.
Warns the user in case a destination address on the Send screen is a known "internal" address that's not labelled as `new`.
Edit: Currently, we'd not allow sending to that address. Alternatively, we could also just show the warning but allow sending Any preferences @dergigi @theborakompanioni?
=> feat: show address reuse warning

src/components/Balance.jsx, src/components/fb/FidelityBondSteps.module.css, src/components/fb/FidelityBondSteps.tsx
Resolves #400.
Stacks the jars on mobile, decreases the balance font size a little bit and wraps the jars onto a new line on bigger screens if space runs out.
=> fix: fidelity bonds jar selecotor spacing

src/components/DisplayAccountsOverlay.module.css, src/components/DisplayAccountsOverlay.tsx
Fixes a small artifact in the jar overlay header and the `onKeyDown` handling (did not fire when the outer most element lost focus).
=> fix: spacing in jar overlay header and `onKeyDown`

src/components/fb/FidelityBondSteps.tsx
Resolves #398.
Do not display info text if array of "utxos about to be frozen" is empty.
=> fix: do not display freeze info when all utxos have been selected

src/components/CurrentWalletAdvanced.tsx, src/components/Earn.jsx, src/components/fb/CreateFidelityBond.jsx, src/context/WalletContext.tsx, src/hooks/BalanceSummary.test.tsx
Part of #381.
Moves filtering utxos for Fidelity Bonds from multiple components into `WalletContext`.
Instead of just holding the filtered utxo array, a new "summary" dictionary holding a single attribute `fbOutputs` is introduced, in case additional information comes up. e.g. if two outputs are present, the most valuable and hence "active" fb can be determined (this is not done at the moment), the human readable "expiry time" or other stats and metrics we do not yet present to the user.
Hope I have found any component that uses FBs and adapted it to use the newly introduced approach.
=> refactor: move filtering for Fidelity Bonds to `WalletContext`

src/components/Cheatsheet.tsx
Since [jamdocs.org](https://jamdocs.org/) is now live, let's link to the appropriate site there instead.
--> https://jamdocs.org/interface/00-cheatsheet/
=> feat(cheatsheet): link to jamdocs.org

.github/workflows/build.yml, package-lock.json, package.json, src/components/Earn.jsx, src/components/Earn.module.css, src/components/Receive.jsx, src/components/Receive.module.css, src/components/Send.module.css, src/index.css
Fixes #348.
Updates dependencies. Jam now successfully builds with node `v16.15.1` (and also latest LTS `v16.16.0`) and npm `v8.11.0`.
Updated dependencies:
- react-bootstrap from `v2.4.0` to [`v2.5.0-beta.1`](https://github.com/react-bootstrap/react-bootstrap/releases/tag/v2.5.0-beta.1)
- react-router-bootstrap from `v0.26.1` to [`v0.26.2`](https://github.com/react-bootstrap/react-router-bootstrap/blob/master/CHANGELOG.md#0262-2022-07-11)
- bootstrap from `v5.1.3` to [`v5.2.0`](https://github.com/twbs/bootstrap/releases/tag/v5.2.0)
Removed dependencies:
- moving-letters `v1.0.1` (unused)
=> deps: update dependencies

src/components/Jam.jsx, src/i18n/locales/en/translation.json
Add a similar check for reused addresses on the Jam page as it already exists on the Send page.
Before this PR, only duplicate address entries in the form inputs have been checked.
After this PR is applied, address validation is extended to all addresses already known to Jam.
=> feat: prevent address reuse on Jam page

src/components/DisplayBranch.module.css, src/components/DisplayBranch.tsx, src/index.css
Fixes small oversights after updating bootstrap in dark theme.
Concerning components:
- font and border colors in accordion body in `CurrentWalletAdvanced`
- font color of cancel button in Fidelity Bond form (Earn page)
Before/After
=> fix: text and border colors after bootstrap update

src/components/Earn.jsx
Fixing a small oversight on the Earn page. `class` => `className`.
=> fix: invalid DOM property 'class' on Earn page

src/index.css
Again a slip on my side.. :disappointed: 
This fixes the button color of "light" buttons in dark mode after a bootstrap update. 
Really hope this is the last one.
=> fix: color of light-button in dark mode

public/sprite.svg, src/components/App.jsx
In https://github.com/joinmarket-webui/jam/pull/439 I swapped the "file" icon from an outlined version to a filled version because that looks better on the settings page. However, in the footer -- where we use the same icon for the cheatsheet -- the outlined version looks better. So I changed it back to be outlined for the cheatsheet and stay filled on the settings page.
**Before:**
**After:**
=> fix: cheatsheet icon

src/components/Earn.jsx, src/constants/features.ts
Removes the feature flag and enables the orderbook for all users.
Can be merged once #434 is integrated.
=> feat: remove feature flag and enable orderbook for all users

src/components/Send.jsx, src/components/Send.module.css, src/i18n/locales/en/translation.json
Closes #385.
Before this PR a payment was initiated immediately after pressing the submit button.
When this PR is applied, a user has the chance to review the given values and possibly catch some input errors before the payment is initiated.
Any improvements or suggestions are welcome.
(e.g. Would it be better to move the privacy info text to the title bar instead of having an own space in the modal body?)
=> feat: payment confirm modal

src/components/EarnReport.module.css, src/components/EarnReport.test.tsx, src/components/EarnReport.tsx, src/i18n/locales/en/translation.json, src/libs/JmWalletApi.ts
Adds ~~pagination,~~ sorting and filtering to Earnings Report overlay.
Was not quite sure how to best style the pagination. Not that happy with the result. Suggestions welcome!
Also, any ideas for improved wording of the table headings?
=> feat: add sorting and filtering to earn report

src/context/ServiceInfoContext.tsx, src/context/WalletContext.tsx, src/libs/JmWalletApi.ts, src/session.ts
Must have been lost during a refactoring, as I am sure this has been supported before.
This readds the API token to the `/session` request.
This request will have additional data in the upcoming JM release, such as `offerlist`, `nickname` and `schedule`.
Also, as this requests checks the validity of the token, it will end the current session if a users logs in form another browser window.
=> fix: pass api token to session request

src/libs/JmWalletApi.ts
It seems passing it as string was needed before but is not needed anymore.
To stay in line with the [API  documentation ](https://joinmarket-org.github.io/joinmarket-clientserver/api/#operation/directsend) the `mixdepth` property when sending a payment (direct-send as well as initiating a collaborative transaction) is now serialized as `integer` instead of `string`.
Know that this does not change any functionality and worked without issues before, it just removes a possible "surprise" for any dev glancing over the code.
=> fix: pass mixdepth prop as number in request body

docker/regtest/init-setup.sh, src/libs/JmWalletApi.ts
Before this commit, values of `POST /maker/start` have been passed as int/decimal types.
After this commit, they well be passed [according to the api docs](https://joinmarket-org.github.io/joinmarket-clientserver/api/#operation/startmaker) as strings.
This prevents an exception on the backend `builtins.TypeError: a bytes-like object is required, not 'float'`. It seemed to still have worked fine before (at least for absolute offers).
=> fix: serialize values of `/maker/start` request body as strings

docker/regtest/dockerfile-deps/joinmarket/directory_node/Dockerfile, docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile
Current state of `master` in the backend repo does signature verification of lobsodium and tor (https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1323). gpg has always been installed in Jam's official docker images (during the install phase), but not in the development environment which leads to failing builds when building from the current `master` branch.
=> dev: install gpg in regtest containers

src/components/EarnReport.tsx, src/i18n/locales/en/translation.json
As suggested by @openoms in the [Community Call #21](https://bitcointv.com/w/tcebpxai765AnALer87fsU?start=17m16s) (at 17m16s), this commit removes the "Fee" column from the Earnings Report.
Since the Miner Fee Contribution is always zero, this value (`fee`) is the same as "earned" (`earnedAmount`).
=> ui: remove column 'fee' from Earn Report

src/components/Orderbook.tsx, src/libs/JmObwatchApi.ts
Resolves #455.
Before this PR, the orderbook was "refreshed" by just refetching the data.
After this PR a `POST` request to `/refreshorderbook` is made beforehand to check for timed-out counterparties.
=> fix: refresh orderbook

src/components/Jam.jsx, src/libs/JmWalletApi.ts
In https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1324 the scheduler option `mixdepthsource` has been removed as the scheduler will automatically start from the first funded account and hence this param does not make much sense anymore.
This commit removes this value from the API request.
~~It can only be merged once https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1324 has been applied.~~ Applied! Rebuild your development environment with the latest changes from master.
=> fix: remove jar source from scheduler options

src/components/Earn.jsx, src/components/Orderbook.module.css, src/components/Orderbook.tsx, src/i18n/locales/en/translation.json
Closes #413.
This does not actually display the nickname (counterparty ID), but lets the user highlight his own orders, as the nickname is already shown on the Earn page (see #461).
First attempt was to just filter the orderbook for the users orders by using the nickname as search value.
However, opted for highlighting the row instead, as this provides the functionality to sort the data and provide more insights and better hints about the positions of your own orders within the orderbook. Let me know what you think.
=> feat: highlight own orders in orderbook

docker/regtest/dockerfile-deps/joinmarket/directory_node/Dockerfile, docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile
Companion change of https://github.com/joinmarket-webui/jam-docker/pull/52 for the regtest environment.
The development environment should as closely as possible incorporate all changes of the prod image.
Neat side effect is, that the images get smaller, even if that is not a high priority objective for the dev setup.
=> dev: bullseye as base image for regtest containers

src/components/Jam.jsx, src/i18n/locales/en/translation.json
Resolves #468.
Uses new `schedule` property of the `serviceInfo` object to display the scheduler progress instead of polling the `/schedule` endpoint.
=> refactor: leverage session request for polling schedule

src/components/Send.module.css
Fixes a small visual glitch on invalid input forms containing a button, e.g. sweep button.
=> fix: proper margin for sweep button on invalid inputs

src/i18n/locales/en/translation.json, src/i18n/locales/fr/translation.json
Always wanted to rename this, and now is the time! 😁 
Thanks to #474 it will only be visible on mobile anyway.
See also https://jamdocs.org/about/#about-the-name
=> feat: rename "Joining" to "Jamming"

src/components/App.jsx, src/components/Wallet.jsx
Before this commit, a user that logs into an active wallet from a second tab/browser, had the first tab/browser not redirect to the unlock wallet page if route `/wallet` was active.
After this commit, the will redirect to the "unlock wallet" page (like all other routes, e.g. `/jam`, `/send`, etc.).
This has really only been the case for route `/wallet`.
It can be tested by navigating to `/wallet` and unlocking the wallet from a second browser/tab.
It should then redirect properly. The secondary instance can be used as a regression test - it still has this bug included.
Additional fix coming out of this: Wallet name on unlock page should only be a link to `/wallet` if the wallet is active **and** unlocked by the current user.
=> fix: redirect to home if no wallet is active on route `/wallet`

src/components/TablePagination.tsx, src/components/jar_details/JarDetailsOverlay.module.css, src/components/jar_details/JarDetailsOverlay.tsx
UI improvements on small screens.
This is a step towards the new Figma layouts.
=> ui: improve layout of JarDetailsOverlay on small screens

src/components/jars/Jar.module.css
This PR changes the cursor when hovering over Jars to open the detailed view from 'pointer' to 'zoom-in'.
Saw it on Figma and thought it was easy to do.
If you don't think this is a good idea, please feel free to just close the PR.
=> ui: use 'zoom-in' cursor when hovering over jars on main page

src/components/fb/CreateFidelityBond.jsx, src/i18n/locales/en/translation.json
Small i18n fixes:
- add missing translation for key `earn.fidelity_bond.review_inputs.text_primary_button_error`
- fix typo in key `.error.loading_address` -> `.error_loading_address`
This has come up when trying to create a fidelity bond with a wallet that does not support fidelity bonds. Jam, by default, will always generate fb-enabled wallets. If we want to prevent users with unsupported wallets from even seeing the form, Jam would have to make an additional http call prior to that - so it might not be worth it.
Question is: Should we append the phrase "Your wallet might not support fidelity bonds" or "Please make sure your wallet supports fidelity bonds", or something like that?
=> chore(i18n): add missing translations for fidelity bonds form

src/components/Send.jsx, src/i18n/locales/en/translation.json, src/i18n/locales/fr/translation.json
Before this PR, the submit button on the Send page has been disabled, if the requirements for collaborative transactions were not met.
After this PR, the warnings are still displayed, but the button is enabled and a payment can be attempted.
Why this change? The functionality has been disabled, as single collaborative transactions have no retry mechanism in place (unlike the scheduled sweep) and users had no real hint on how to recover, in case a transaction gets "stuck". With #497 resolved, users can now abort/cancel single collaborative transactions, hence the button can safely be enabled.
However, if preconditions are not fulfilled, the transaction will likely either get "stuck" (e.g. when a utxo with <5 confs is used) or will be aborted by the server (20% rule, no retries left) - …
=> fix: do not disable submit button on warnings on Send page

src/components/Send.jsx, src/i18n/locales/en/translation.json
Consistent button labeling on Send page.
Additionally, change text from  "Ignore warning & send" to "Ignore warning & try send".
=> fix: consistent button text during screen initialization

src/components/Navbar.jsx
I don't know how I got this wrong, but the order I did in #496 has earn before send:
```
Receive  »  Earn  »  Send  |  Sweep
``` 
Because of the new flow it should be **send before earn**, to get `cj-out` for FB:
```
Receive  »  Send  »  Earn  |  Sweep
```
I got it right in [the docs](http://localhost:8000/interface/00-cheatsheet/) and in the cheatsheet (#496) - but I messed it up in the previous PR (#490).
---
=> fix(navbar): send before earn

src/components/Send.jsx, src/i18n/locales/en/translation.json, src/i18n/locales/fr/translation.json, src/index.css
Resolves #499.
Applying classes `small`, `slashed-zeroes` and `break-word` to make sure the text is readable on all screens (and not clipped).
In next iterations, this is message is better presented as toast message, which has been an idea for a while (not done in this PR).
=> feat(send): show txid on successful direct-send

src/components/jar_details/JarDetailsOverlay.module.css, src/components/jar_details/JarDetailsOverlay.tsx, src/components/jar_details/UtxoDetailModule.module.css, src/components/jar_details/UtxoDetailModule.tsx, src/components/jar_details/UtxoList.tsx, src/i18n/locales/en/translation.json
Resolves #440.
Changes:
- show sum of selected utxos
- adapt margins/paddings to better match figma screens
- wording according to figma:
- "Jar Details" -> "Details"
- "Freeze/unfreeze selected" -> "Freeze/unfreeze"
=> feat: show sum of selected utxos

package-lock.json, package.json, src/components/App.tsx, src/components/CreateWallet.test.jsx, src/components/MainWalletView.jsx, src/components/Receive.jsx, src/components/Settings.test.jsx, src/components/Wallet.test.jsx, src/components/Wallets.test.jsx, src/index.tsx, src/testUtils.tsx
Updates dependency `react-router-dom` from v6.3.0 to v6.4.1.
Originally wanted to leverage the [new `loader` feature](https://reactrouter.com/en/main/route/loader#loader) to separate data loading from view rendering.
This will be done in a follow-up PR as we often update context data which cannot be done in a satisfactory way yet (see https://github.com/remix-run/react-router/issues/9324).
=> deps: update `react-router-dom` from v6.3.0 to v6.4.1

src/components/Jam.jsx
Closes #267.
Before this PR, the Sweep screen did not wait for an operation to start/stop and assumed the operation will succeed.
After this PR, the screen will show a loading indicator till the service has been successfully started/stopped.
=> fix(sweep): wait for scheduler start/stop

src/i18n/locales/en/translation.json
Change phrasing in orderbook summary: "order" -> "offer".
The "orderbook" does not consist of "orders" but of "offers". A taker is someone that makes an "order" based on "offers".
e.g.
-  "42 orders by 21 counterparties" -> "42 offers by 21 counterparties"
- "Highlight my orders" -> "Highlight my offers"
=> i18n(orderbook): order -> offer

src/components/Modal.tsx, src/components/Send.jsx, src/components/settings/FeeConfigModal.tsx, src/hooks/Fees.test.ts, src/hooks/Fees.ts, src/i18n/locales/en/translation.json, src/utils.ts
Partly addresses #518.
Display values based on fee settings in the confirmation modal of the Send page.
"Mining fee target" will be displayed either as "targeted blocks" or "sats/vByte" (randomized or exact):
e.g.
- "Next block" (`tx_fees := 1`)
- "In 6 blocks" (`tx_fees := 6`)
- "In 1,000 blocks" (`tx_fees := 1000`)
- "1.001 sats/vByte" (`tx_fees := 1001`, `tx_fees_factor := 0`)
- "9.1 - 10.9 sats/vByte" (`tx_fees := 10000`, `tx_fees_factor := 0.9`)
"Estimated Max. Collaborator Fee" will be displayed for collaborative transactions.
Calculation can be found here: https://github.com/joinmarket-webui/jam/blob/feat/display-fee-settings-in-send/src/hooks/Fees.ts#L69-L70 (Tests: https://github.com/joinmarket-webui/jam/blob/feat/display-fee-settings-in-send/src/hooks/Fees.test.ts#L22-L69)
=> feat: display fee settings on Send page

src/components/settings/FeeConfigModal.tsx, src/i18n/locales/en/translation.json
When the fee target is low, JM sometimes constructs transactions, which are declined from being relayed. In order to mitigate such situations, the minimum fee target (when provided in sats/vbyte) has been increased from 1 sat/vByte to 3 sats/vByte, and fee randomization lowered from 0 - 100% to 0 - 50%.
This can only mitigate the problem and should be seen as a temporary solution till the situation has been addressed upstream.
See https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1360#issuecomment-1259638764 and https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1360#issuecomment-1262295463
=> fix(fees): mitigate construction of non-forwardable transactions

docker/regtest/common.sh, docker/regtest/docker-compose-common.yml, docker/regtest/docker-compose.yml, docker/regtest/fund-wallet.sh, docker/regtest/init-setup.sh, docker/regtest/readme.md
This PR adds a third JM regtest instance and starts an additional maker service during initialization with `npm run regtest:init`.
It is an attempt to make the development setup more resilient to maker timeouts. Setup script takes slightly longer and cpu usage during development will increase a bit.
Also adapted some regtest settings for faster/easier testing:
- actually set `maker_timeout_sec` on primary instance -> was `maker_timeout_sec` instead of `jm_maker_timeout_sec`
- set `taker_utxo_age` from 5 to 1 on primary instance (this revealed that coinjoin precondition warning message must be parameterized)
- do not set `tx_broadcast` - was `self` (use default value `random-peer`); you'll see more "tx already in chain" warnings, which is expected behaviour.
Start and initialize your dev …
=> regtest: start additional maker service

src/components/Jam.jsx, src/components/ScheduleProgress.jsx
Was able to reduce the time from >=10min to ~3min for scheduled sweeps.
This is achieved by adapting the "test mode" settings:
- reducing destination addresses from 3 to 1
- reducing the time between transactions
- reducing minimum transaction count per Jar from 2 to 1
```
2022-10-04 07:54:30,991 [DEBUG]  connection was made, starting client.
[...]
2022-10-04 07:57:58,889 [INFO]  Coinjoin completed correctly
```
Example schedule:
```
[
[0, 0, 1, "INTERNAL", 0.05, 16, 0], 
[1, 0, 1, "bcrt1qc8s0d5cnhkqyp4fae7epj4up36sjz8gtvp7ru6", 0.03, 16, 0]
]
```
Destination address count can be adapted by changing the `DEST_ADDRESS_COUNT_TEST` constant.
Invoke a sweep and verify that ~2 transactions (instead of ~6) are scheduled in quick succession.
If everything works correctly, the operation should …
=> regtest: speed up scheduled sweep for testing

.github/workflows/codeql-analysis.yml
These changes only affect github workflows. No other changes were made.
> CodeQL Action v1 will be deprecated on December 7th, 2022. Please upgrade to v2. For more information, see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
Warnings when building current master branch: https://github.com/joinmarket-webui/jam/actions/runs/3320776538
Fixed (no more warnings) in this branch: https://github.com/joinmarket-webui/jam/actions/runs/3329343820
=> deps(workflow): update github actions to newest versions

src/components/Jam.jsx
Closes  #542.
This PR adds a button to quickly adapt the fee settings before sweeping.
Fee settings are randomized on every startup, so this can serve as a hint to review and/or adapt them before doing a sweep.
@editwentyone This is just a suggestion. Please close if you think it is redundant.
=> feat: quickly review/adapt fee settings before sweeping

src/components/EarnReport.module.css, src/components/EarnReport.tsx, src/components/LogOverlay.module.css, src/components/LogOverlay.tsx, src/components/Orderbook.module.css, src/components/Orderbook.tsx, src/index.css
Changes:
- Striped table rows on Earn Report
- Improved mobile view for Earn Report
- Improved mobile view for Log Overlay
All fullscreen overlays (JarDetails, Orderbook, Earn Report, Log Overlay) should now have identical styles on mobile devices and small screens.
Still quite a bit duplicate code - this has not been refactored in this PR.
To test the Log Overlay changes, you need to start the UI with `npm run dev:start:secondary`!
To test the Earn Report and see the changes, your need to start the maker at least twice (to get two rows in the report).
=> ui: improve all overlay content on small screens

src/components/Send.jsx, src/components/Send.module.css
Before this PR, Jam displayed and sent a fractional number as collaborators to the backend (which rounded down to the nearest int). After this commit is applied the number of collaborators as always parsed and displayed as integer.
Before:
After:
=> fix: no. of collaborators as integer

src/components/jar_details/JarDetailsOverlay.module.css, src/components/jar_details/JarDetailsOverlay.tsx, src/i18n/locales/en/translation.json
Closes #517.
I added total balance next to the tab selector so that it will be always visible.
=> feat: Show jar total amount in detail view

src/components/CreateWallet.jsx
Small cosmetic change. Adds padding to the success message after seed phrase confirmation.
=> chore(ui): add padding to seed backup success message

src/components/SegmentedTabs.module.css, src/components/SegmentedTabs.tsx, src/components/jar_details/JarDetailsOverlay.module.css, src/components/jar_details/JarDetailsOverlay.tsx
Closes https://github.com/joinmarket-webui/jam/issues/528
This PR moves the "UTXOS | DETAILS" tab out of the header and places it just below the header instead.
Here is screenshots of the changes:
I also made sure that all of the other instances of `<SegmentedHeader/>` still look good:
=> ISSUE-528: improve JarDetailsOverlay header

src/components/Jars.module.css, src/components/jars/Jar.module.css, src/components/jars/Jar.tsx
Small PR to align the main wallet view with Figma screens.
Places the jar info (name and balance) next to the jar icon on small screens.
=> ui(Jars): move jar info next to icon on small screens

src/components/Balance.module.css, src/components/Balance.test.tsx, src/components/Balance.tsx, src/components/Navbar.module.css, src/components/Navbar.tsx, src/components/fb/FidelityBondSteps.module.css
Small refactoring PR: Uses typescript for the `Balance` component.
Also, avoids some flickering by immediately evaluating `displayMode` instead of hiding the balance briefly by default.
=> refactor(Balance): jsx to tsx

src/components/Accordion.tsx, src/components/Earn.jsx, src/components/Earn.module.css, src/components/Orderbook.tsx, src/components/Receive.jsx, src/components/Receive.module.css, src/components/Send/CollaboratorsSelector.tsx, src/components/Send/index.tsx, src/components/fb/SpendFidelityBondModal.tsx, src/i18n/locales/en/translation.json, src/i18n/locales/fr/translation.json
This solves [#508](https://github.com/joinmarket-webui/jam/issues/508).
I decided to not over-engineering the new `Accordion` component but we may take into consideration possible future side effects of unmounting children components (which will likely be form fields) when user closes the accordion: for example, if we will use it with some Formik registered components, we may (or may not) get some unwanted behaviour about validation or field values being correctly send in the form submit (take my consideration with a grain of salt, I haven't verified it).
Any feedback is appreciated 🧡 
[Development soundtrack](https://open.spotify.com/album/5MYbCAee86KlqqCNbouhhG?si=i5Q65Bn_SfG4tjCGOvYckw) 🎧
=> Send: Hide "number of collaborators" behind send options

package-lock.json, package.json, src/components/App.tsx, src/components/ErrorPage.tsx, src/components/PageTitle.tsx, src/constants/debugFeatures.ts, src/constants/routes.ts, src/i18n/locales/en/translation.json
Before this commit, in case there was an error, a generic error page had been shown.
After this commit, a dedicated error page, including the navbar, the footer and with a link to create an issue on GitHub, will be displayed.
Whenever you browse the app, this page should never render in the first place, as all error are to be handled by the actual component. However, some errors slip through (e.g. with the date parsing bug in safari #584) and then, the user should be presented with a better view.
The page is really just the bare minimum. The error is unexpected and in most cases, cannot be resolved by the user without support.
In order for this to work properly, the dependency `react-router-dom` has been upgraded from `v6.4.3` to `v6.6.1`.
In dev mode (when starting with `npm run …
=> feat: add dedicated error page

src/components/fb/CreateFidelityBond.jsx, src/components/fb/ExistingFidelityBond.tsx, src/components/fb/FidelityBondSteps.tsx, src/components/fb/utils.ts, src/context/WalletContext.tsx
It seems Safari is not able to construct `Date` objects from strings formatted as `yyyy-MM-dd 00:00:00` (see [stackoverflow#4310953](https://stackoverflow.com/questions/4310953/invalid-date-in-safari)).
Before this commit, as soon as a user on Safari created a fidelity bond, an error was thrown and the page became Earn page did not render.
After this commit, the fidelity bond is shown correctly and the Earn page renders successfully.
This is an _untested_ change, as every attempt to run Safari failed on my workstation. It be great if someone can verify that it works as expected. However, the root problem should be addressed, as all date objects are instantiated with a timestamp (type `number`) which every browser supports.
=> fix: correctly render existing bonds in Safari

docker/regtest/dockerfile-deps/joinmarket/directory_node/Dockerfile, docker/regtest/dockerfile-deps/joinmarket/directory_node/default.cfg, docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile, docker/regtest/dockerfile-deps/joinmarket/latest/default.cfg, docker/regtest/dockerfile-deps/joinmarket/webui-standalone/default.cfg
Fixes https://github.com/joinmarket-webui/jam/issues/581
Quick workaround to make the regtest environment compatible with the current state of master ([`ea7a6e`](https://github.com/JoinMarket-Org/joinmarket-clientserver/commit/ea7a6e1a5b9dde5eb0af2b22d831e843f4800020)) again. This can be removed [once the install script is fixed upstream](https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1396#issuecomment-1369975749).
Also, adapts the payjoin server port from `8080` to `8082` according to [`2749da1`](https://github.com/JoinMarket-Org/joinmarket-clientserver/commit/2749da174ac0cf7c5186b88af15b2970df5dce49) - included in JM `v0.9.9`.
=> fix: install python3-venv in regtest environment

src/components/Earn.jsx, src/components/fb/SpendFidelityBondModal.tsx
There has been a bug when unlocking an expired fidelity bond: After the tx had been broadcasted, the success screen disappeared, as the modal was hidden as soon as no FB was present anymore.
With this fix, the success screen is shown correctly after an expired FB has been unlocked.
On master, verify you can reproduce the bug: After you spend an expired Fidelity Bond, no success screen is displayed.
Then checkout this branch and repeat the procedure. This time the success screen should be displayed.
=> fix(fb): correctly display success screen after unlocking fb

src/components/settings/FeeConfigModal.tsx
Resolves #602.
This seems to have been just an oversight. 
Before this PR, the fee modal did not let users specify 0.0001% as relative fee limit.
After this PR, 0.0001% is allowed and accepted as valid value. 
Tested by setting "absolute fee limit" to 10 sats (makers in regest use 250 sats as absolute fee)  and "relative fee limit" to 0.0001% (factor: 0.000001), then sending a collaborative transaction sweeping Jar A with 2 collaborators on regtest. 
Success :heavy_check_mark:
Verify the transaction by watching the logs with `npm run regtest:logs:jmwalletd`.
=> fix(fees): allow input for relative fee limit of 0.0001%

src/components/settings/FeeConfigModal.tsx
Requires JM `v0.9.9` or greater -> needs #585 to be merged and a recreated dev environment by running `npm run regtest:rebuild`!
Before this commit, minimum in Jam was 3 sats/vbyte as prior ot JM `v0.9.9`, this resulted in an error, as JM used to little fees and the tx was rejected from the mempool.
When this commit is applied, setting the tx fee to 1 sat/vbyte is allowed.
Set your tx fees to 1 sat/vbyte (with 0% randomization) and try to spend an expired fidelity bond.
=> fix(fees): allow min tx fee of 1sat/vbyte

src/setupProxy.js
Users reported problems on [Raspibolt following this guide](https://raspibolt.org/guide/bonus/bitcoin/Jam.html).
See https://github.com/joinmarket-webui/jam/issues/608#issuecomment-1451831421
This seems to fix their problem while also having the development environment in functional state.
=> chore: use `127.0.0.1` instead of `localhost` in setupProxy.js

docker/regtest/docker-compose.yml
Adds container `getumbrel/btc-rpc-explorer` to the regtest environment.
This is useful if you want to inspect your local chain or transactions in general.
=> regtest: add block explorer to dev environment

docker/regtest/docker-compose.yml
added port mapping for bitcoind so that external wallet software can access the regtest env to test the sweep function
=> dev(regtest): update to docker-compose

src/components/JarSelectorModal.tsx, src/components/Jars.module.css, src/components/Jars.tsx, src/components/Receive.jsx, src/components/Send/Send.module.css, src/components/Send/index.tsx, src/components/fb/FidelityBondSteps.tsx, src/components/jars/Jar.module.css, src/components/jars/Jar.tsx
Resolves #634.
Displays the frozen or locked balance in the Jars component.
=> feat(balance): display frozen balance on jars

public/sprite.svg, src/components/Send/index.tsx, src/components/jars/Jar.module.css, src/components/jars/Jar.tsx
Part of #516.
This PR contains following changes
- add a warning sign to the selected jar on the Send page, if some preconditions are not met (e.g. not enough confirmations, no tries left, etc.).
- add a checkmark to the "payment success" alert
- improve "collaborative transaction in progress" alert
=> ui(send): add warn sign to selected jar on precondition violations

src/components/App.tsx, src/components/CopyButton.tsx, src/components/CreateWallet.jsx, src/components/Earn.jsx, src/components/Earn.module.css, src/components/ImportWallet.tsx, src/components/Jam.module.css, src/components/Jam.tsx, src/components/MainWalletView.module.css, src/components/MnemonicWordInput.module.css, src/components/MnemonicWordInput.tsx, src/components/Navbar.tsx, src/components/Onboarding.jsx, src/components/Onboarding.module.css, src/components/Receive.jsx, src/components/Receive.module.css, src/components/Send/Send.module.css, src/components/Send/index.tsx, src/components/WalletCreationConfirmation.tsx, src/components/WalletCreationForm.module.css, src/components/WalletCreationForm.tsx, src/components/fb/CreateFidelityBond.module.css, src/components/fb/CreateFidelityBond.tsx, src/components/fb/ExistingFidelityBond.tsx, src/components/fb/FidelityBondSteps.tsx, src/components/jar_details/DisplayBranch.tsx, src/constants/debugFeatures.ts, src/i18n/locales/en/translation.json, src/index.css
Resolves https://github.com/joinmarket-webui/jam/issues/639
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
=> fix(ui): consistent button styles

.gitignore, src/components/App.test.tsx, src/components/CreateWallet.test.jsx, src/components/Settings.jsx, src/components/Wallet.test.tsx, src/components/Wallets.jsx, src/components/Wallets.test.jsx, src/constants/features.ts, src/context/ServiceInfoContext.tsx, src/globals.d.ts, src/libs/JmWalletApi.ts
Resolves https://github.com/joinmarket-webui/jam/issues/637.
Using the new `/getinfo` endpoint to provide the ability to use backend version based feature toggles.
e.g. as "import wallet" feature will be available with JM v0.9.10, this enables hiding/disabling the button.
Change the port from the dev JM backend (port `28183`) to the secondary JM backend (port `29183`), which runs an older version. Restart the ui (`npm run dev:start`) and verify that the "Import Wallet" button is not displayed anymore.
```diff
diff --git a/src/setupProxy.js b/src/setupProxy.js
index 360592a..6cdcfa3 100644
--- a/src/setupProxy.js
+++ b/src/setupProxy.js
@@ -7,7 +7,7 @@ const SUPPORTED_BACKENDS = [BACKEND_NATIVE, BACKEND_STANDALONE]
const {
PUBLIC_URL = '',
JAM_BACKEND = BACKEND_NATIVE,
- …
```
=> feat: backend version based feature toggles

src/components/Accordion.tsx, src/components/ImportWallet.tsx, src/i18n/locales/en/translation.json
Following changes should improve user experience and prevent some mistakes while importing wallets by adding visual feedback:
- Adds a max blockheight value: `10_000_000` - just to prevent errors during import  (should be lower than the current blockheight anyway)
- Adds a max gaplimit value: `10_000` - rather high , but users should not be prevented from doing it, if they really want to
- Warn on "large" gaplimit values: any value greater than `250` (arbitrarily chosen) will display a warning
=> chore(import): display warning on large gaplimit values

src/components/Footer.tsx, src/context/ServiceInfoContext.tsx, src/utils.test.ts, src/utils.ts, tsconfig.json
Displays the ui/backend version in the info modal.
=> feat: display ui/backend version

docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile, src/components/App.tsx, src/components/BitcoinQR.jsx, src/components/CoinjoinPreconditionViolationAlert.tsx, src/components/CreateWallet.jsx, src/components/EarnReport.tsx, src/components/ImportWallet.tsx, src/components/LogOverlay.tsx, src/components/ToggleSwitch.tsx, src/components/Wallets.jsx, src/components/Wallets.test.jsx, src/components/jar_details/DisplayBranch.tsx, src/constants/config.ts, src/constants/features.ts, src/context/ServiceConfigContext.tsx, src/context/ServiceInfoContext.tsx, src/context/WalletContext.tsx, src/index.tsx, src/libs/JmWalletApi.ts, src/session.ts, src/testUtils.tsx
Resolves #663.
This PR adds handling for the new JWT auth mechanism.
From [JSON-RPC-API-using-jmwalletd.md#rules-about-making-requests](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/JSON-RPC-API-using-jmwalletd.md#rules-about-making-requests):
> On initially creating, unlocking or recovering a wallet, a new access and refresh token will be sent in response, the former is valid for only 30 minutes and must be used for any authenticated call, the former is valid for 4 hours and can be used to request a new access token, ideally before access token expiration to avoid unauthorized response from authenticated endpoint and in any case, before refresh token expiration.
The token is refreshed every 22.5 minutes (30min * 0.75). In dev mode more often (every 60 …
=>  feat: new authentication mechanism (access/refresh token)

src/components/Send/index.tsx, src/utils.ts
Nothing fancy: Scroll above the fold after a successful payment to focus the "payment successful" or "collaborative transaction in progress" message.
=> chore(ui): scroll to page top after successful payment

src/components/PaymentConfirmModal.tsx, src/components/settings/FeeConfigModal.tsx, src/i18n/locales/en/translation.json
Resolves #654.
Adapts the texts and fee calculation for backends >=v0.9.10.
=> fix(fee-randomization): fix fee range in PaymentConfirmModal

src/context/ServiceInfoContext.tsx, src/context/WalletContext.tsx, src/context/WebsocketContext.jsx, src/utils.ts
Before these changes, the `/session` endpoint has been polled with `setInterval` - i.e. rescheduled to run every 10 seconds, regardless of the response duration. On slow connection, e.g. over Tor, this can lead to requests queuing up.
After this commit, a new request is made 10 seconds _after_ the previous response arrived, which mitigates the behaviour described above.
=> chore: debounce polling of session info

src/components/Send/index.tsx, src/utils.ts
Before this commit, the first funded jar has been preselected as source jar.
After this commit, no jar will be preselected.
This was a request by @editwentyone.
Additionally, it fixes a strange bug: Scrolling to the top of the page did not work properly in all browsers.
=> chore: do not preselect jar on send page

src/components/App.test.tsx, src/components/Footer.tsx, src/i18n/locales/en/translation.json
Before this commit, the label on the websocket indicator just stated "connected" or "disconnected", which caused some confusion. 
After this commit, it will be labelled  "Websocket conntected" or "Websocket disconnected". Also, if the websocket is disconnected, the icon is coloured gray instead of red, as Jam will work normally without a stable websocket connection (UI responsiveness will be slower, but is functioning).
<br />
=> ui(footer): improve label and colors of websocket indicator

src/components/Settings.tsx, src/i18n/locales/en/translation.json
This is just a proposal, feel free to close it, if you think it is not a good idea.
I do not quite  see the use of a "create wallet" button from the settings page.
A wallet can already be created from the main view when no wallet is active.
This PR will remove the button from the settings page.
What do you think?
=> chore: remove create wallet button from settings page

docker/regtest/docker-compose.yml, src/components/App.tsx, src/components/DevSetupPage.tsx, src/components/ErrorPage.tsx, src/components/Footer.tsx, src/components/Navbar.tsx, src/constants/debugFeatures.ts, src/constants/routes.ts, src/i18n/locales/en/translation.json, src/index.css
A page only shown in development mode that contains links and other information about useful sites available in the regtest environment:
- regtest block explorer
- additional jm/jam instances (makers)
- example error page
- wallet/auth info
Goal is to make it easier for new devs to get to know the setup quickly.
=> chore(dev): dev setup info page

src/components/jar_details/DisplayBranch.tsx, src/components/jar_details/JarDetailsOverlay.tsx, src/context/ServiceInfoContext.tsx
..as those derive public keys from an unexpected derivation depth.
See upstream issue https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1586
So, best thing for now is to temporarily do not display any xpub, instead of a "wrong" one. What do you think?
=> chore: do not display xpubs

src/components/LogOverlay.module.css, src/components/LogOverlay.tsx, src/components/Orderbook.module.css, src/components/Orderbook.tsx, src/components/Settings.tsx
The feature to show the log file is not available on all platforms.
Before this commit, the "show logs" button has only been displayed if a special endpoint indicates it is enabled.
However, this is somewhat confusing, as the endpoint is not available in the regtest environment.
So, when this commit is applied, the button will always be shown while developing.
With `npm run dev:start`, the log endpoint will return an error (as it is not implemented in the dev environment, since this is interacting with a "native" JM instance) and a message is displayed to run `npm run dev:start:secondary` (which interacts with an instance in the `standalone` image, that has the log feature enabled!).
Additionally, this moves the menu item from section "Markets" to "Wallet".
=> dev: always show logs button in dev mode

src/components/CreateWallet.test.tsx, src/components/WalletCreationForm.tsx, src/i18n/locales/en/translation.json, src/utils.ts
Resolves #683.
Before this commit, the wallet name has been validated only on the backend.
After this commit is applied, it will also be validated by the frontend.
The validation is a bit more strict than "necessary", only numbers, letters and `_` (underscore) will be allowed from now on.
=> chore: validate wallet name

src/components/Earn.tsx, src/components/Orderbook.tsx, src/libs/JmObwatchApi.ts, src/utils.ts
Closes https://github.com/joinmarket-webui/jam/issues/454.
Closes https://github.com/joinmarket-webui/jam/issues/561.
- Fetches `orderbook.json` instead of parsing the html table to get data.
- Uses normalized fidelity bond value
- Removes column "Miner Fee Contribution"
=> fix: use orderbook.json instead of parsing html table

src/components/CreateWallet.test.tsx, src/components/CreateWallet.tsx, src/components/ImportWallet.tsx, src/components/Wallet.test.tsx, src/components/Wallet.tsx, src/components/Wallets.test.tsx, src/components/Wallets.tsx, src/i18n/locales/en/translation.json
Resolves #682.
- Change phrasing from "active"/"inactive" to "unlocked"/"locked".
- Display "rescanning" alert in `Wallets` and `CreateWallet` component
=> ui: improve phrasing and display rescanning alert

package-lock.json, package.json, src/components/App.test.tsx, src/context/WebsocketContext.jsx, src/setupTests.ts
- `jest-watch-typeahead` to v2.2.2
- `jest-websocket-mock` to v2.5.0
=> build(deps): update dependencies

src/components/Balance.module.css, src/components/Balance.test.tsx, src/components/Balance.tsx, src/components/jars/Jar.module.css, src/components/jars/Jar.tsx
Resolves #694.
Hides the currency symbol for frozen balances in component `Jar`.
Also, available and frozen balance use the same font size.
=> ui(Jar): hide currency symbol of frozen balance

src/components/Jam.tsx, src/components/ToggleSwitch.tsx, src/components/settings/FeeConfigModal.tsx, src/constants/debugFeatures.ts
Ability to reset fee values in dev mode.
Some fee properties (`max_cj_fee_abs` and `max_cj_fee_rel`) do not have default values if JM is installed from scratch.
You can now reset those fee values if you want to test what the UI looks like, when a user does not have these values configured.
Misc:
- also added the "dev" badge to the test toggle on the scheduler page
- Start the app in dev mode with `npm run dev:start`
- Go to settings -> Click "Adjust fee limits"
- Click the "Reset form values" button (notice how the form becomes invalid)
- Click "Save" - form should not be able to be submitted
- Toggle (disable) "Enable form validation"
- Now click "Save" again - config will be updated
- Visit "Send" or "Sweep" page and verify the alert message saying fee config values are missing
<br /> …
=> dev: ability to reset fee values in dev mode

src/components/Send/DestinationInputField.tsx, src/components/Send/FeeBreakdown.tsx, src/components/Send/SendForm.tsx
Resolves #707.
Shows the expected collaborator fees in the unit of the users choice.
Jam can still display values in sats (instead of BTC) - so the toggle will influence the displayed unit (as opposed to always show in BTC). Getting rid of the conversion to sats has been thought about, but should be done in a separate issues if needed.
=> chore(send): align unit in collaborators fee breakdown

package-lock.json, src/components/CopyButton.tsx, src/components/Earn.tsx, src/components/Footer.tsx, src/components/JarSelectorModal.module.css, src/components/JarSelectorModal.tsx, src/components/Jars.tsx, src/components/Modal.tsx, src/components/Navbar.module.css, src/components/Navbar.tsx, src/components/Receive.module.css, src/components/Receive.tsx, src/components/ShareButton.tsx, src/index.css
Small changes suggested by @editwentyone.
- Receive: Move "Get new address" button below qrcode
- Main: Change position of tooltip for "Wallet distribution" from "right" to "bottom"
- Mobile Menu: Increase font size and center text
Bonus: Use standard modal layout for "app info" modal.
=> chore: small ui changes suggested by @editwentyone

src/components/Modal.tsx, src/components/Send/DestinationInputField.tsx, src/components/Send/index.tsx, src/components/fb/SpendFidelityBondModal.tsx
Fixes the payment confirm modal size that has been broken in #709.
=> fix(ui): adapt payment confirm size

src/components/App.tsx, src/components/Jars.module.css, src/components/Jars.tsx, src/components/Layout.tsx, src/components/MainWalletView.module.css, src/components/MainWalletView.tsx, src/components/Receive.module.css, src/components/Send/SourceJarSelector.module.css, src/components/jars/Jar.module.css, src/components/jars/Jar.tsx
- larger jars and buttons on main wallet view
- use fluid container (container-xl) and switch column sizes from
```
md={10} lg={8} xl={6}
```
to
```
lg={10} xl={10} xxl={8}
```
<br />
<br />
<br />
<br />
<br />
<br />
=> ui: fluid container with wider layout

docker/regtest/docker-compose.yml
This updates regtest Bitcoin Core from v25 to v26.
Should serve as a reminder for everyone using JM/Jam wanting to upgrade to Bitcoin Core v26: You need to add arg `-deprecatedrpc=create_bdb` (at start or in conf file).
See https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1571 for more information.
Meta question: How will this work for users with Umbrel/Citadel/RaspiBlitz/etc.?
=> dev(regtest): update bitcoin core to v26

src/components/Jars.module.css, src/components/MainWalletView.tsx, src/components/Navbar.tsx, src/components/PaymentConfirmModal.module.css, src/components/SegmentedTabs.module.css, src/components/SegmentedTabs.tsx, src/components/jar_details/JarDetailsOverlay.tsx, src/components/jars/Jar.module.css, src/components/jars/Jar.tsx
Resolves #713.
Selectable Jars can now be focused.
Please test by navigating through all form elements on the Send page with your keyboard.
Additionally:
- Close Jar Details Modal on key "Escape"
- Add help cursor on hover over info icons (e.g. Main Wallet View, Payment Confirm Modal)
- Segmented Tabs can now be focused (e.g. Fee Modal, Earn Options)
=> fix: selectable ui elements

docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile, src/components/Earn.tsx, src/components/PaymentConfirmModal.tsx, src/components/SegmentedTabs.module.css, src/components/SegmentedTabs.tsx, src/components/Send/AmountInputField.module.css, src/components/Send/AmountInputField.tsx, src/components/Send/DestinationInputField.module.css, src/components/Send/DestinationInputField.tsx, src/components/Send/SendForm.module.css, src/components/Send/SendForm.tsx, src/components/Send/index.tsx, src/components/jar_details/JarDetailsOverlay.tsx, src/components/settings/TxFeeInputField.tsx, src/constants/features.ts, src/hooks/Fees.ts, src/i18n/locales/en/translation.json, src/libs/JmWalletApi.ts
Resolves #696.
Enables specifing the tx fee on the send page for direct and collaborative sends.
Only possible with the newest (unreleased) JM version.
Direct send support is already merged (https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1597).
Collaborative send is still being reviewed (https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1612).
TODO:
=> feat: custom tx fee on direct and collaborative send

src/components/Earn.tsx, src/components/PaymentConfirmModal.tsx, src/components/Send/index.tsx, src/components/fb/CreateFidelityBond.tsx, src/components/fb/FidelityBondSteps.tsx, src/components/fb/LockdateForm.tsx, src/components/fb/SpendFidelityBondModal.tsx, src/hooks/WaitForUtxosToBeSpent.ts, src/i18n/locales/en/translation.json, src/index.css
Resolves #610 
Adds the ability to renew an expired fidelity bond.
This will be done with a direct-send creating a "single input, single output transaction" (this might not be what more advanced users want - e.g. CPFP is not possible afterwards). Feedback welcome.
In addition, the "Create FB" confirm dialog will now display the fee settings for the user to review before actually creating the bond.
- Create an expired fidelity bond (only possible in dev mode with `npm run dev:start`)
- Renew expired fidelity bond (also, possibly with lockdate in the past)
- Rinse and repeat!
=> feat: renew fidelity bond

src/components/Earn.tsx
Resolves #726.
Fixes a regression in v0.2.0 that disallowed zero absolute fees on maker offers.
=> fix: allow absolute maker fee of zero

src/components/fb/CreateFidelityBond.tsx, src/components/fb/FidelityBondSteps.tsx, src/components/fb/LockdateForm.tsx, src/i18n/locales/en/translation.json
This PR fixes #616 
Implementation is done in lockdateForm.js component, that shows a warning message while selecting expiry date whenever a user creates a new fidelity bond.
When is warning message displayed? if there already exists fidelity bonds, and a user create a new one. But he selects an expiry date same as in any of the previous bonds. Then the message is displayed warning the user.
=> 616: (feat) prevent multiple fidelity bonds with same expiry date

src/components/Earn.tsx, src/constants/config.ts, src/i18n/locales/en/translation.json
Fixes #740.
However, this is a temporary fix to prevent the backend from dying.
There should be a follow-up PR that adds better explanation more prominently.
e.g. similar to the  `CoinjoinRequirementSummary`/`CoinjoinRequirementViolation` alerts on "Jam" and "Send".
=> fix(Earn): validate offer minsize

src/components/Orderbook.tsx, src/constants/debugFeatures.ts, src/i18n/locales/en/translation.json
Adds a small hint that it might take some time for an offer to appear in the local order book, e.g. when the maker has just been started recently. This hint will disappear if the current nickname is present in the offer list.
Edit: Screenshots outdated - see below :pray:
=> ui(orderbook): add delay hint to highlighted offer toggle

src/components/Settings.tsx
Locking the wallet can take some time (sometimes a few seconds, e.g. via Tor). This avoids additional requests being made if the button is clicked while a request is in-flight.
(It is not totally obvious in the screenshot, but the button is disabled)
=> chore(ui): disable lock button while locking wallet

.github/workflows/codeql-analysis.yml
Update `codeql` github actions from `v2` to `v3`.
Context: https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, github/codeql-action/init@v2, github/codeql-action/autobuild@v2, github/codeql-action/analyze@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> ci(deps): update codeql actions from v2 to v3

src/components/fb/CreateFidelityBond.module.css, src/components/fb/CreateFidelityBond.tsx, src/i18n/locales/en/translation.json
this PR fixes #760 
When user clicks "configure fidelity bond" modal appears like this:
Whole flow to create new bond works fine on my setup.
Open to any kind of suggestions.
PS: Cross Button at top-right functions same as cancel button. I've kept it as it will be useful for later UI design.
=> modal instead of dropdown for new FB creation form

src/components/App.tsx, src/components/Orderbook.tsx, src/libs/JmObwatchApi.ts
Resolves #754.
Displays amount and expiration date of fidelity bonds in the orderbook overlay.
Create a fidelity bond for one of the dev makers (e.g. on localhost:29080 - you need to stop the maker, create a fidelity bond, and restart the maker again). Then, reload the orderbook on the main dev instance and verify that the correct Fidelity Bond information is displayed.
=> feat(orderbook): show fidelity bond value and locktime

package-lock.json, package.json, src/setupProxy.js
Resolves #768.
Updates dev dependency `http-proxy-middleware` from `v2.0.6` to `v3.0.0`.
See the migration guide for more information: https://github.com/chimurai/http-proxy-middleware/blob/master/MIGRATION.md
- checkout branch
- run `npm install`
- run `npm run dev:start` and/or `npm run start`
- verify everything is running properly as before (e.g. create/import a wallet, attempt collaborative transaction, etc.)
=> build(dev-deps): update http-proxy-middleware from v2.0.6 to v3.0.0

src/components/fb/CreateFidelityBond.tsx
fixes #775 
The alert message has been shifted inside modal.
However I was not able to produce the error locally, so its requested to produce the error locally while reviewing it. and please let know if it works fine.
PS: If anyone gets to know how to produce error, I would love to learn it as well.
=> fix(fb): display error alert in modal

src/components/Wallet.test.tsx, src/components/Wallet.tsx, src/components/Wallets.test.tsx
This partly reverts a previous change and rephrases the label on wallets that are currently loaded from "unlocked" to "active".
Mainly tries to avoid confusion as mentioned in #774.
=> ui(wallet): rephrase wallet label from 'unlocked' to 'active'

src/components/Settings.tsx, src/i18n/locales/de/translation.json, src/i18n/locales/en/translation.json, src/i18n/locales/fr/translation.json, src/i18n/locales/it/translation.json, src/i18n/locales/pt_BR/translation.json, src/i18n/locales/zh_Hans/translation.json, src/i18n/locales/zh_Hant/translation.json
=> ui: remove twitter link from settings page

src/components/MainWalletView.tsx
Most wallets have the ability to switch the unit of account (BTC or sats) by clicking at the balance.
Before this commit, the balance on the main wallet view has been a visibility toggle only. If a user clicked the balance it either showed the balance in the preferred unit or hid the balance.
e.g. BTC -> hidden -> BTC -> hidden, etc.
After this commit, a click will change the unit of the balance and only with a subsequent click toggles the visibility.
e.g. BTC -> sats -> hidden -> BTC -> sats, etc.
=> feat: unit and visibility toggle on main wallet view

public/sprite.svg, src/components/Balance.module.css, src/components/Balance.tsx, src/components/Divider.module.css, src/components/Divider.tsx, src/components/JarSelectorModal.tsx, src/components/MainWalletView.module.css, src/components/MainWalletView.tsx, src/components/Modal.module.css, src/components/Modal.tsx, src/components/Send/AmountInputField.tsx, src/components/Send/SendForm.tsx, src/components/Send/ShowUtxos.module.css, src/components/Send/ShowUtxos.tsx, src/components/Send/SourceJarSelector.tsx, src/components/jar_details/UtxoList.tsx, src/components/settings/FeeConfigModal.module.css, src/components/settings/FeeConfigModal.tsx, src/context/WalletContext.tsx, src/i18n/locales/en/translation.json
Follow-up to #771.
TBD.
Still TODO:
=> follow-up(PR771): quick freeze/unfreeze

src/components/BitcoinAmountInput.test.tsx, src/components/BitcoinAmountInput.tsx
This PR fixes #799 
Fixed the amount input field to correctly interpret `1.0` as `1 BTC`. Previously, it was incorrectly treated as a much smaller value; for example, entering `0.1` was considered `0.00000001 BTC`.
=> fixed amount input field to properly interpret BTC

src/components/Jam.tsx, src/components/SchedulerConfirmationModal.module.css, src/components/SchedulerConfirmationModal.tsx, src/i18n/locales/en/translation.json
This PR completes #796 
Made a Confirmation Modal that starts the scheduler only when the user confirms it.
=> feat: add SchedulerConfirmationModal component for starting scheduled sweep

src/components/Send/ShowUtxos.module.css, src/components/Send/ShowUtxos.tsx, src/components/jar_details/UtxoList.module.css, src/components/jar_details/UtxoList.tsx, src/components/utxo/Confirmations.module.css, src/components/utxo/Confirmations.tsx, src/components/utxo/UtxoIcon.module.css, src/components/utxo/UtxoIcon.tsx, src/components/utxo/UtxoTags.module.css, src/components/utxo/UtxoTags.tsx, src/components/utxo/utils.ts, src/context/WalletContext.tsx
This is a follow-up PR to #771 which introduces some UTXO related UI components that can be reused across different pages or interface elements, i.e. the UTXO list in the Jar Details View and the Quick Freeze Modal on the Send page.
Some details are subject to discussion, e.g. the color scheme and/or icons.
This is not a pixel-perfect representation of the Figma designs, but simplifies the current state and increases reusability.
Next step would be alignment and adaptation of the wording (not done in this PR).
=> refactor: align utxo list and modal components

src/components/PaymentConfirmModal.tsx, src/components/Send/SendForm.tsx, src/components/Send/ShowUtxos.module.css, src/components/Send/ShowUtxos.tsx, src/components/Send/SourceJarSelector.tsx, src/components/Send/index.tsx, src/components/jar_details/UtxoList.tsx, src/i18n/locales/en/translation.json
This PR fixes #773 
Changes:
1. User are now able to review their `considered UTXOs` before performing a sweep
2. Successful implementation of
=> UI : Show considered UTXOs before performing transaction

src/components/Orderbook.tsx
Fixes #770 
Makes the text of the balances on the tooltip consistent.
Light-Mode:
Dark-Mode:
=> Improves readablity of balances on the tooltip in light mode

public/sprite.svg, src/components/ScheduleProgress.module.css, src/components/ScheduleProgress.tsx
=> (ui) Static Cooking Pot 

src/components/Settings.tsx
it's a dead account
I was also removed from the Jam docs https://github.com/joinmarket-webui/jamdocs/pull/61, as JM doesn't want to link to this account either
=> Settings: remove link to dead JM twitter

.github/workflows/build.yml, src/components/App.tsx, src/components/Settings.test.tsx, src/i18n/locales/de/translation.json, src/i18n/locales/en/translation.json, src/i18n/locales/fr/translation.json, src/i18n/locales/it/translation.json, src/i18n/locales/pt_BR/translation.json, src/i18n/locales/zh_Hans/translation.json, src/i18n/locales/zh_Hant/translation.json
Follow-up to https://github.com/joinmarket-webui/jam/pull/830.
- Removes unused translations
- Fixes the Settings page unit test
- Run GitHub workflows on `devel` branch
=> chore(i18n): remove unused translations

src/components/Footer.tsx
=> add matrix to footer

src/components/RescanChain.tsx, src/components/Settings.tsx, src/i18n/locales/en/translation.json
Fixes #833
Added translations to the settings page rescan option and for the entire rescan page and also removed the dev tag and made the rescan feature available in production as well
=> Added rescan page translations and removed dev mode tag

CONTRIBUTING.md, docker/regtest/readme.md, docs/developing.md, package.json, src/components/LogOverlay.tsx
Small improvement for local development:
Changes the command for running in dev mode from `npm run dev:start` to `npm run dev` (e.g. as next.js does).
=> dev: use `npm run dev` to run app in dev mode

src/components/jars/Jar.tsx
Fixes #839.
A side effect of this is, that it will not show the tooltip anymore if you focus the jars (e.g. by using the keyboard), which is not ideal but feels okay.
How to test? Follow the steps in  #839 and verify the tooltip now correctly disappears.
=> fix(main): properly fade out jar tooltips

src/components/App.tsx, src/components/Earn.tsx, src/context/WalletContext.tsx, src/index.tsx
This PR attempts to prevent fetching UTXO labels when it is not strictly necessary.
The request to `/display` is quite expensive for heavily used wallets and users report it can take up to several minutes!
On initially unlocking a wallet the request is made at least once. After that, it will only be done when there is no label present for a UTXO returned in the `/utxo` endpoint response.
Do some transactions and verify that the new UTXOs all have the correct label attached. e.g. `deposit`, `cj-out`, etc.
`/display` requests previously always executed in the Jar Details Modal and the Send page.
=> perf: optimize api request

src/components/fb/LockdateForm.test.tsx, src/components/fb/LockdateForm.tsx
Fixes: #852 
The default `timeZone` for `Intl.DateTimeFormat` is based on the user's timezone, so because I'm behind UTC it get's shifted some hours back which leads to incorrect formatting of the month. Because we send the date in UTC to `Intl.DateTimeFormat` we can set UTC explicitly as the `timeZone` to solve the issue.
The test case `_selectableMonths / should display month name` was not passing on my end, and now it does.
Also fixed a supposedly typo on the `describe('_selectableMonth')` to reflect the correct name of the function that is being tested. I can adjust it back if you don't want unnecessary diff on the squashed commit.
=> Fix months order across timezones

src/components/PaymentConfirmModal.tsx, src/components/Send/ShowUtxos.tsx, src/components/Send/SourceJarSelector.tsx, src/components/Send/index.tsx, src/components/utxo/Confirmations.module.css, src/i18n/locales/en/translation.json
This PR tries to enhance the phrasing in the Quick Freeze and Payment Confirm modal on the Send page.
Distinction is done between "Eligible UTXOs" (for non-sweeps) and "Selected UTXOs" (for sweeps).
Please let me know what you think - feedback is desperately needed!
Also, if you have better versions of the texts and phrases in mind - please post them here as comment or as change suggestion! :pray: 
- Visually adjust the "confirmations" block
- Title from `"Select UTXOs to be considered"` to just `"Select UTXOs"`
- Phrase `"The following UTXOs are considered in the transaction. "` to one of the following
```json
"subtitle_zero": "Please select one or more UTXOs for possible inclusion in the transaction.",
"subtitle_one": "The selected UTXO is eligible for inclusion in the transaction.", …
```
=> chore: small quick freeze modal adaptions

CHANGELOG.md, package-lock.json, package.json
=> chore(release): v0.3.0

src/components/jar_details/JarDetailsOverlay.module.css, src/components/jar_details/JarDetailsOverlay.tsx, src/i18n/locales/en/translation.json
Fixes #856
displays the disabled buttons along with a note on why the freeze/unfreeze operations are currently disabled.
https://github.com/user-attachments/assets/56fe0de3-8d72-4590-bbd8-921ac2dbcb9c
=> added a note when freeze/unfreeze is disabled in Jar Details View

src/components/Send/ShowUtxos.module.css
Fixes the color of unfrozen and expired fidelity bond utxos in dark mode, e.g. in utxo selection and confirm modal.
(This should not have affected anybody if Jam has been exclusively used to control a JM node, as unfreezing Fidelity Bonds is not supported via the UI).
=> fix(ui): fidelity bond utxo row color in dark mode

src/components/JarSelectorModal.tsx, src/components/fb/SpendFidelityBondModal.tsx
Small fix to align the buttons in the jar selection modal.
Now both buttons (cancel and confirm) have the same size.
=> fix(ui): fix button alignment in jar selection modal

src/components/jar_details/JarDetailsOverlay.tsx
fix #911 
- Fixed: the total displayed for a jar now sums the live UTXO values instead of using the possibly-stale jar.account_balance coming from /display.
- Passed String(utxosBalance) to the Balance component for the total line in the UTXO tab.
=> chore: update jar balance

package-lock.json, package.json, src/App.tsx, src/components/CreateWallet.tsx, src/components/Login.tsx, src/components/Logs.tsx, src/components/Navbar.tsx, src/components/SwitchWallet.tsx, src/components/settings/SeedPhraseDialog.tsx, src/components/settings/Settings.tsx, src/hooks/useFeatures.ts, src/hooks/useWalletDisplay/index.ts, src/lib/config.ts, src/lib/session.ts, src/store/authStore.ts
Replaces custom handling of session storage with zustand.
Only the authentication related properties have been refactored.
"rescan" properties are still handled the previous way.
Let me know what you think @nischal-shetty2
=> refactor(v2): use zustand for auth store
