.github/workflows/build.yml
src/index.css

Perform the lint, test and build tasks on master and pull requests targeting master.

Add build workflow

---

DEVELOPING.md
README.md
package.json

Moved the development related part of the readme to a dedicated DEVELOPING.md. Also added some more details on teh code formatting approach and a link to some troubleshooting tips. Thanks to @dennisreimann for the hint! 🙏

feat: developer docs

---

src/components/App.jsx

Fixes #35 . Thanks for finding @dnlggr.

cleanup: remove broken websocket connection

---

src/components/Settings.jsx

In the call today we talked about changing the wording on the theme selector to make it more clear the current state of the application and what the button does.

feat: improve wording in settings

---

src/components/Send.jsx

Fixes #83
This is only done on the "send" page currently. Have not experienced this behaviour on other requests than `/direct-send`.
Before:
After:

fix: extract error message of text/html response

---

src/components/App.jsx
src/components/Earn.jsx
src/components/Send.jsx
src/components/ToggleSwitch.jsx
src/index.css

Also fixes 1 of 2 points in https://github.com/joinmarket-webui/joinmarket-webui/issues/87.

feat: update earn page

---

src/components/App.jsx
src/index.css

Resolves #90.
Text is just something off the top of my head. Let me know if you have a better idea please!
Semi happy with the looks but probably good enough.

feat: add alpha disclaimer

---

README.md

Not much to say. 😅 
Do we have a PR for Citadel as well?

fix: add integration pr links to readme

---

src/components/App.jsx

This should've gone into #92 but I forgot to push the commit. 🤦‍♂️

fix: footer spacing and links

---

src/components/App.jsx
src/components/Onboarding.jsx
src/index.css

Improves the onboarding layout on mobile. Previously it looked a bit to crammed on small screens.
I also DRYed it up a bit so that content is rendered based off an array of objects rather than repeating the layout code for every page.

fix: improve onboarding mobile layout

---

public/index.html
src/components/Sprite.jsx
src/index.jsx
src/libs/JmWalletApi.js

This reverts commit 4a3b16847e71a79e8b0b57ccf20c2edb0df5bf98.
There seems to be a problem with reloads on subpages as mentioned in https://github.com/joinmarket-webui/joinmarket-webui/pull/124#issuecomment-1054134877.
Sorry @dennisreimann  and @dnlggr . I failed to do my part on this : (
Let's revert it for now and apply the changes once we have a solution. Is this okay for everyone?

Revert "feat: allow for deployment in subdirectory (#124)"

---

src/components/Receive.jsx

Remove privacy levels on receive screen in magic mode

---

docker/regtest/docker-compose.yml
docker/regtest/dockerfile-deps/joinmarket/nginx/default.conf.template
docker/regtest/dockerfile-deps/nginx/default.conf.template
public/index.html
src/components/Sprite.jsx
src/context/WebsocketContext.jsx
src/index.jsx
src/libs/JmWalletApi.js
src/setupProxy.js

One more try at #124.
@dnlggr the [9a5904e](https://github.com/joinmarket-webui/joinmarket-webui/pull/129/commits/9a5904e51abe17bc754166f2f533042209df01b9) commit solves the issue mentioned in you last comment of the previous PR for me.

feat: allow for deployment in subdirectory

---

package-lock.json

`package.json` and `package-lock.json` weren't in sync after #146.

chore: run npm install

---

CHANGELOG.md
package-lock.json
package.json

chore(release): prepare v0.0.4

---

src/components/App.jsx
src/components/App.test.jsx
src/components/CreateWallet.jsx
src/components/CurrentWalletAdvanced.jsx
src/components/CurrentWalletMagic.jsx
src/components/DisplayAccountUTXOs.jsx
src/components/DisplayAccounts.jsx
src/components/DisplayUTXOs.jsx
src/components/Earn.jsx
src/components/Navbar.jsx
src/components/Onboarding.jsx
src/components/Receive.jsx
src/components/Send.jsx
src/components/Settings.jsx
src/components/Settings.test.jsx
src/components/Wallet.jsx
src/components/Wallet.test.jsx
src/i18n/locales/en/translation.json
src/utils.js

Translate all screen. I hope I didn't miss to much. Naming is certainly not ideal everywhere and there are quite a few repetitions still. Open for suggestions!

feat: translate screens

---

CHANGELOG.md
package-lock.json
package.json

chore(release): prepare v0.0.5

---

src/components/App.jsx
src/components/CreateWallet.jsx
src/components/CurrentWalletMagic.jsx
src/components/DisplayAccounts.jsx
src/components/Navbar.jsx
src/components/Wallet.jsx
src/components/Wallets.jsx
src/constants/routes.ts

This PR adds route constants, by doing this we will:
- Prevent typos when specifying a route
- Make it easier for new devs to get familiarised with all current routes/pages

refactor: Add route constants

---

src/components/Wallet.jsx
src/components/Wallet.module.css

resolves #237 
https://user-images.githubusercontent.com/16882830/167547134-2685e04e-9185-47d4-bcaa-75a18a58b3dd.mov

ui: prevent password unlock input from resizing on error

---

src/components/ActivityIndicators.jsx
src/components/CurrentWalletMagic.jsx
src/components/Navbar.jsx
src/components/Wallet.jsx

Maps to what is probably the most common user flow:
```
[ Receive -> Jam / Earn -> Send ]
```

feat: rearrange order of tabs

---

src/components/Jam.jsx
src/i18n/locales/en/translation.json

Closes #261
Text of error message is: "Reusing addresses has negative implications such as diminished privacy and reduced security. It is highly discouraged and therefore prevented."
Please add your suggestions here if you have a more appropriate phrase in mind.

feat: prevent address reuse on Jam screen

---

docker/regtest/readme.md

- Add "Common flow" section at the top of readme
- Note about new local Directory Node
- Note about `npm run regtest:mine`

docs: describe 'common flow' in regtest readme

---

src/context/ServiceInfoContext.tsx

Similar to #297.
This commit waits for `/session` requests to finish for attempting another one.
This is needed as some requests can take longer (e.g. `/wallet/create`) than the periodic interval (which is currently `10_000` ms).

fix: prevent unnecessary session requests

---

src/components/App.jsx
src/components/App.test.jsx
src/components/Onboarding.jsx
src/i18n/locales/en/translation.json
src/i18n/locales/fr/translation.json

chore: pre-alpha -> beta

---

src/components/CurrentWalletMagic.module.css

Fixes the styles of the _Receive_ and _Send_ buttons on the main wallet page.

fix: css merge error

---

CHANGELOG.md
package-lock.json
package.json

chore(release): prepare v0.0.7

---

src/components/App.jsx
src/components/Cheatsheet.tsx
src/components/CurrentWalletAdvanced.tsx
src/constants/features.ts

Remove the fidelity bond feature flag.

fix: remove fidelity bond feature flag

---

CHANGELOG.md
package-lock.json
package.json

chore(release): prepare v0.0.8

---

src/components/EarnReport.tsx
src/i18n/locales/en/translation.json

Resolves #408.
Things like CSV export would be cool as well but that can wait.

feat: improve earn report

---

src/components/fb/CreateFidelityBond.jsx
src/components/fb/CreateFidelityBond.module.css
src/i18n/locales/en/translation.json

Resolves #365.
Adds a description to the fidelity bond entry point (in case a fidelity bond already exists) that allows us to explain how a second fidelity bond works.
Wording suggestions welcome!

feat: add description for second fidelity bond

---

src/i18n/locales/en/translation.json

feat(cheatsheet): re-word to remove 'yield'

---

src/components/Cheatsheet.tsx

Didn't see that there were more external links when doing #427 🤦

feat(cheatsheet): link to jamdocs.org

---

public/sprite.svg
src/components/Onboarding.jsx
src/components/Settings.jsx
src/i18n/locales/en/translation.json

Add link to jamdocs.org in settings and onboarding flow.
Resolves #428

feat(settings): add links to docs

---

src/components/fb/ExistingFidelityBond.jsx

fix: remove logs

---

CHANGELOG.md
package-lock.json
package.json

chore(release): prepare v0.0.10

---

CONTRIBUTING.md
docker/regtest/common.sh
docker/regtest/fund-wallet.sh
docker/regtest/init-setup.sh
docker/regtest/readme.md

Renames the regtest default wallet from "funded" to "Satoshi".
Makes for nicer screenshots. :camera_flash:

regtest: rename default wallet to Satoshi

---

src/components/App.jsx
src/components/Footer.jsx

Externalize `Footer` component.
Small adaption - has always bothered me.
No functional changes. Just separating components.

refactor: externalize Footer component

---

src/components/Jam.jsx

Tiny fix: Reloads wallet info after a scheduled sweep is stopped manually. 
Before this PR the displayed wallet balance was outdated and not updated when manually stopping a scheduled sweep.
After this PR the wallet balance will reflect the actual balance after manually stopping a scheduled sweep.
Additional: Removes a unneeded delay when stopping the scheduled sweep.
This does not (fully) address https://github.com/joinmarket-webui/jam/issues/251 or https://github.com/joinmarket-webui/jam/issues/489.

fix: reload wallet info after stopping scheduler manually

---

src/components/Cheatsheet.tsx
src/i18n/locales/en/translation.json

Resolves #482 
<details>
<summary>(old screenshot for comparison)</summary>
</details>

feat(cheatsheet): update order

---

CHANGELOG.md
package-lock.json
package.json

chore(release): prepare v0.1.0

---

docker/regtest/dockerfile-deps/joinmarket/directory_node/default.cfg
docker/regtest/dockerfile-deps/joinmarket/latest/default.cfg
docker/regtest/dockerfile-deps/joinmarket/latest/jam-entrypoint.sh
docker/regtest/dockerfile-deps/joinmarket/webui-standalone/default.cfg

Companion PR of https://github.com/joinmarket-webui/jam-docker/pull/66 for the local regtest environment.

regtest: randomize max fee settings

---

CHANGELOG.md
package-lock.json
package.json

chore(release): v0.1.1

---

src/components/Earn.jsx
src/i18n/locales/en/translation.json

ui(earn): improve offer summary display

---

src/components/Orderbook.module.css
src/components/Orderbook.tsx

ui(orderbook): improve readability with alternating colors

---

CHANGELOG.md
package-lock.json
package.json

chore(release): v0.1.3

---

CHANGELOG.md
package-lock.json
package.json

chore(release): v0.1.4

---

src/components/Wallet.module.css
src/components/Wallet.test.tsx
src/components/Wallet.tsx
src/components/Wallets.jsx
src/index.css

Small PR to add lock/unlock icon to the "login" screen.

ui(Wallet): add lock/unlock icon

---

src/components/Send/CollaboratorsSelector.module.css
src/components/Send/CollaboratorsSelector.tsx
src/components/Send/Send.module.css
src/components/Send/index.tsx

Follow up to  #582.
Just some small refactoring of the `Send` components.
- adapt types, type names
- fix loading issue
- camelCase css classnames
- externalize styles of `CollaboratorsSelector` component

refactor(send): follow-up PR to #582

---

CHANGELOG.md
package-lock.json
package.json

chore(release): v0.1.5

---

docker/regtest/docker-compose.yml

Upgrades bitcoin core from v23 to v25 in local dev environment.

dev(regtest): upgrade bitcoin core from v23 to v25

---

docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile

This fixes a wallet import edge case.

config: use joinmarket v0.9.10

---

CHANGELOG.md
package-lock.json
package.json

chore(release): v0.1.6

---

CHANGELOG.md
package-lock.json
package.json

chore(release): v0.2.0

---

src/i18n/languages.ts

fixed incorrect description values for the two Chinese translations

Update languages.ts to replace incorrect descriptions  for Chinese translations

---

src/i18n/locales/en/translation.json

bit of a nit
"Jam is anything but" is not good English afaik.
so change the text to `Jam is not`, to match other places where it is mentioned:
https://github.com/joinmarket-webui/jam/blob/66a100d932aaff9c061d5f5b0136a04d3add1c29/src/components/Onboarding.tsx#L82
https://github.com/joinmarket-webui/jam/blob/66a100d932aaff9c061d5f5b0136a04d3add1c29/src/i18n/locales/en/translation.json#L54

chore(i18n): update splashscreen_warning_text: improve english

---

package.json
src/components/Navbar.tsx
src/components/settings/CollaboratorFeesForm.tsx
src/components/settings/FeeLimitDialog.tsx
src/components/settings/MiningFeesForm.tsx
src/components/settings/Settings.tsx
src/components/settings/TxFeeInputField.tsx
src/components/ui/DevBadge.tsx
src/components/ui/dialog.tsx
src/components/ui/switch.tsx
src/constants/jam.ts
src/constants/jm.ts
src/i18n/locales/en/translation.json
src/lib/utils.test.ts
src/lib/utils.ts

Implements the fee limit dialog with collaborator fees and mining fee drop downs.

feat: add FeeLimitDialog component for managing fee settings

---

CHANGELOG.md
package-lock.json
package.json

chore(release): v0.4.1
